// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 15.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorForGH
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ScenarioForGH : ScenarioForGHBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"/* Copyright 2017-2018 REAL.NET group
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\nnamespace GeneratorForGH\n{\n\tusing System;\n\tusing System.Linq;\n\tusing System.Reac" +
                    "tive;\n\tusing System.Reactive.Linq;\n\tusing System.Reactive.Subjects;\n\tusing Robot" +
                    "Simulation;\n\tusing Trik;\n\n\tpublic class GeneratedCode\n    {\n");

List<Repo.INode> modelNodes = new List<Repo.INode>();
foreach (var x in Repository.Model("GreenhouseTestModel").Nodes) {
	modelNodes.Add(x);
}
	
foreach (var x in modelNodes) { 
            this.Write("\n\t\tprivate static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(classOfElement(x.Name)));
            this.Write(" element");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(";\n");
 } 
            this.Write("\n\n\t\tprivate static void Main(string[] args)\n\t\t{\n            Console.WriteLine(\"In" +
                    "itial values:\");\n");
 
foreach (var x in modelNodes) { 
	var index = modelNodes.IndexOf(x); 
            this.Write("\n\n\t\t\telement");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(" = new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(classOfElement(x.Name)));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(");\n\t");
 
	if (classOfElement(x.Name) == "Interval")
	{
			var minEnum = x.Attributes.Where(y => y.Name == "min").AsEnumerable();
			var maxEnum = x.Attributes.Where(y => y.Name == "max").AsEnumerable();
			if (minEnum.Any() && maxEnum.Any())
			{
				string min = minEnum.First().StringValue ?? "null";
				string max = maxEnum.First().StringValue ?? "null"; 
            this.Write("\n\n\t\t\telement");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(".Min = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(min));
            this.Write(";\n\t\t\telement");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(".Max = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(max));
            this.Write(";\n            Console.WriteLine(\"Interval {0}: min -- {1}, max -- {2}\", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(min));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(max));
            this.Write(");\n\t\t\t");
}
	}
	if (classOfElement(x.Name) == "Operation")
	{
            this.Write("\n\n\t\t\telement");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(".Kind = \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(kindOfOperation(x.Name)));
            this.Write("\";\n\t");
}
            this.Write("\n\n\t\t\tIObservable<int> observable");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(" =\n\t\t\t\t\t\tSystem.Reactive.Linq.Observable.FromEventPattern<int>(\n\t\t\t\t\t\t\th => eleme" +
                    "nt");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(".Event += h,\n\t\t\t\t\t\t\th => element");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(".Event -= h)\n\t\t\t\t\t\t\t.Select(e => e.EventArgs)\n\t\t\t\t\t\t\t.Synchronize().DistinctUntil" +
                    "Changed();\n\t\t\tIObserver<int> observer");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(" = Observer.Create<int>(x => element");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(".Action(x));\n\t\t\tISubject<int> reactElement");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(" = Subject.Create<int>(observer");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(", observable");
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            this.Write(");\n\t    ");

}
            this.Write("\n\n");


foreach (var x in Repository.Model("GreenhouseTestModel").Edges) {
	if (classOfElement(x.To.Name) == "Operation") { 
            this.Write("\n\n\t\t\telement");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf((Repo.INode)x.To)));
            this.Write(".IncomingValues.Add(");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf((Repo.INode)x.From)));
            this.Write(", null);\n\t");
 }
}

            this.Write("\n\n\t\t\t// index of the element and index of the reactElement which is made on it\'s " +
                    "basis are the same \n");


int j = 0;
foreach (var x in Repository.Model("GreenhouseTestModel").Edges) 
{ 
	var source = x.From as Repo.INode;
	var target = x.To as Repo.INode; 
            this.Write("\n\t\t\tvar sub");
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            this.Write(" = reactElement");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(source)));
            this.Write(".Subscribe(reactElement");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(target)));
            this.Write(");\n");

	j++;
} 
            if (!TestWithRobotSimulation) { 
            this.Write("\n\t\t\tvar robot = new Model();\n            ");
 }

            // defining ports for sensors, actuators and connecting them with real(or RobotSimulation) sensors/actuators 
			foreach (var x in modelNodes) { 
				if (classOfElement(x.Name) == "Sensor") { 
					var port = x.Attributes.Where(y => y.Name == "port").AsEnumerable();
					if (port.Any())
					{
						string p = port.First().StringValue; 
                        if (TestWithRobotSimulation) { 
            this.Write("\n            SensorSim sensorSim");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(" = new SensorSim(");
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            this.Write(");\n\t\t\tsensorSim");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(".Index = ");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(";\n            Console.WriteLine(\"Sensor{0}: sensor at port {1}\", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            this.Write(");\n\n            IObservable<int> observableForSimulation");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(" =\n\t\t\t\t\t\tSystem.Reactive.Linq.Observable.FromEventPattern<int>(\n\t\t\t\t\t\t\th => senso" +
                    "rSim");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(".Event += h,\n\t\t\t\t\t\t\th => sensorSim");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(".Event -= h)\n\t\t\t\t\t\t\t.Select(e => e.EventArgs)\n\t\t\t\t\t\t\t.Synchronize().DistinctUntil" +
                    "Changed();\n\n            observableForSimulation");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(".Subscribe(reactElement");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(");\n                        ");
 }
                        else { 
            this.Write("\n\n\t\t\tvar s<#= modelNodes.IndexOf(x) #> = robot.AnalogSensors[Trik.Sensor.A<#= p #" +
                    ">].ToObservable().DistinctUntilChanged();\n\t\t\ts<#= modelNodes.IndexOf(x) #>.Subsc" +
                    "ribe(reactElement<#= modelNodes.IndexOf(x) #>);\n                        ");
 }
                     }
				}
				if (classOfElement(x.Name) == "Actuator") { 
					var port = x.Attributes.Where(y => y.Name == "port").AsEnumerable();
					if (port.Any())
					{
						string p = port.First().StringValue; 
            this.Write("\n\t\t\t\n            Console.WriteLine(\"Actuator{0}: actuator at port {1}\", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            this.Write(");\n\n                        ");
 if (TestWithRobotSimulation) { 
            this.Write("\n\t\t\tIObserver<int> observerForSimulation");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(" = Observer.Create<int>(x => Console.WriteLine(\"----- Actuator at port {0} -- {1}" +
                    "  -----\", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(p));
            this.Write(", x));\n\t\t\treactElement");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(".Subscribe(observerForSimulation");
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNodes.IndexOf(x)));
            this.Write(");\n                        ");
 }
                        else { 
            this.Write("\n            reactElement<#= modelNodes.IndexOf(x) #>.Subscribe(robot.Motors[Trik" +
                    ".Motor.M<#= p #>]);\n                        ");
 }
					}
				}
			} 
            this.Write("\n\n            Console.ReadLine();\n        }\n    }\n}\n\n");
            return this.GenerationEnvironment.ToString();
        }
 
string classOfElement(string name)
{
	switch(name)
	{
		case "aOpenWindow":
			return "Actuator";
		case "aCloseWindow":
			return "Actuator";
		case "aPourSoil":
			return "Actuator";
		case "aAirTemperature":
			return "Sensor";
		case "aSoilTemperature":
			return "Sensor";
		case "aInterval":
			return "Interval";
		case "aAndOperation":
			return "Operation";
		case "aOrOperation":
			return "Operation";
		default:
			return "Sensor";
	}
}

string kindOfOperation(string name)
{
	switch(name)
	{
		case "aAndOperation":
			return "And";
		case "aOrOperation":
			return "Or";
		default:
			return "And";
	}
}

public Repo.IRepo Repository { get; set; }
public bool TestWithRobotSimulation { get; set; }

    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ScenarioForGHBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
