// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SamplesPlugin")]
[assembly: AssemblyProductAttribute("REAL.NET")]
[assembly: AssemblyDescriptionAttribute("Domain-specific modeling toolkit")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const String AssemblyTitle = "SamplesPlugin";
        internal const String AssemblyProduct = "REAL.NET";
        internal const String AssemblyDescription = "Domain-specific modeling toolkit";
        internal const String AssemblyVersion = "0.1";
        internal const String AssemblyFileVersion = "0.1";
        internal const String AssemblyConfiguration = "Release";
    }
}
