// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("ConstraintsMatcher")]
[assembly: AssemblyProduct("REAL.NET")]
[assembly: AssemblyDescription("Domain-specific modeling toolkit")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]
[assembly: AssemblyConfiguration("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "ConstraintsMatcher";
        internal const System.String AssemblyProduct = "REAL.NET";
        internal const System.String AssemblyDescription = "Domain-specific modeling toolkit";
        internal const System.String AssemblyVersion = "0.1";
        internal const System.String AssemblyFileVersion = "0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
