// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Repo")>]
[<assembly: AssemblyProductAttribute("REAL.NET Repository Core")>]
[<assembly: AssemblyDescriptionAttribute("Domain-specific modeling repository")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Repo"
    let [<Literal>] AssemblyProduct = "REAL.NET Repository Core"
    let [<Literal>] AssemblyDescription = "Domain-specific modeling repository"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
