//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hello.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HelloParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IHelloVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.oclFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOclFile([NotNull] HelloParser.OclFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.packageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageName([NotNull] HelloParser.PackageNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.oclExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOclExpressions([NotNull] HelloParser.OclExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] HelloParser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.contextDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContextDeclaration([NotNull] HelloParser.ContextDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.classifierContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassifierContext([NotNull] HelloParser.ClassifierContextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.operationContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationContext([NotNull] HelloParser.OperationContextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.operationName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationName([NotNull] HelloParser.OperationNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList([NotNull] HelloParser.FormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] HelloParser.TypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.collectionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionType([NotNull] HelloParser.CollectionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.oclExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOclExpression([NotNull] HelloParser.OclExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] HelloParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] HelloParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.letExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetExpression([NotNull] HelloParser.LetExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfExpression([NotNull] HelloParser.IfExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExpression([NotNull] HelloParser.LogicalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] HelloParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] HelloParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] HelloParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] HelloParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] HelloParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] HelloParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.propertyCallParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyCallParameters([NotNull] HelloParser.PropertyCallParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] HelloParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiteral([NotNull] HelloParser.EnumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeSpecifier([NotNull] HelloParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.literalCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralCollection([NotNull] HelloParser.LiteralCollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.collectionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionItem([NotNull] HelloParser.CollectionItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.propertyCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyCall([NotNull] HelloParser.PropertyCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.qualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiers([NotNull] HelloParser.QualifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] HelloParser.DeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.pathName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathName([NotNull] HelloParser.PathNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.timeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeExpression([NotNull] HelloParser.TimeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.actualParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualParameterList([NotNull] HelloParser.ActualParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOperator([NotNull] HelloParser.LogicalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.collectionKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionKind([NotNull] HelloParser.CollectionKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] HelloParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOperator([NotNull] HelloParser.AddOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.multiplyOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyOperator([NotNull] HelloParser.MultiplyOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] HelloParser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] HelloParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HelloParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] HelloParser.NumberContext context);
}
