//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hello.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HelloParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IHelloListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.oclFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOclFile([NotNull] HelloParser.OclFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.oclFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOclFile([NotNull] HelloParser.OclFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.packageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageName([NotNull] HelloParser.PackageNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.packageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageName([NotNull] HelloParser.PackageNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.oclExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOclExpressions([NotNull] HelloParser.OclExpressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.oclExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOclExpressions([NotNull] HelloParser.OclExpressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] HelloParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] HelloParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.contextDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContextDeclaration([NotNull] HelloParser.ContextDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.contextDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContextDeclaration([NotNull] HelloParser.ContextDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.classifierContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassifierContext([NotNull] HelloParser.ClassifierContextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.classifierContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassifierContext([NotNull] HelloParser.ClassifierContextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.operationContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperationContext([NotNull] HelloParser.OperationContextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.operationContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperationContext([NotNull] HelloParser.OperationContextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.operationName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperationName([NotNull] HelloParser.OperationNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.operationName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperationName([NotNull] HelloParser.OperationNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterList([NotNull] HelloParser.FormalParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterList([NotNull] HelloParser.FormalParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] HelloParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] HelloParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.collectionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionType([NotNull] HelloParser.CollectionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.collectionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionType([NotNull] HelloParser.CollectionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.oclExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOclExpression([NotNull] HelloParser.OclExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.oclExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOclExpression([NotNull] HelloParser.OclExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] HelloParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] HelloParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] HelloParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] HelloParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.letExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetExpression([NotNull] HelloParser.LetExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.letExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetExpression([NotNull] HelloParser.LetExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExpression([NotNull] HelloParser.IfExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExpression([NotNull] HelloParser.IfExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpression([NotNull] HelloParser.LogicalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpression([NotNull] HelloParser.LogicalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] HelloParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] HelloParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] HelloParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] HelloParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] HelloParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] HelloParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] HelloParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] HelloParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] HelloParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] HelloParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] HelloParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] HelloParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.propertyCallParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyCallParameters([NotNull] HelloParser.PropertyCallParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.propertyCallParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyCallParameters([NotNull] HelloParser.PropertyCallParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] HelloParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] HelloParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumLiteral([NotNull] HelloParser.EnumLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumLiteral([NotNull] HelloParser.EnumLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTypeSpecifier([NotNull] HelloParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTypeSpecifier([NotNull] HelloParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.literalCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralCollection([NotNull] HelloParser.LiteralCollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.literalCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralCollection([NotNull] HelloParser.LiteralCollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.collectionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionItem([NotNull] HelloParser.CollectionItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.collectionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionItem([NotNull] HelloParser.CollectionItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.propertyCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyCall([NotNull] HelloParser.PropertyCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.propertyCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyCall([NotNull] HelloParser.PropertyCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.qualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiers([NotNull] HelloParser.QualifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.qualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiers([NotNull] HelloParser.QualifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] HelloParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] HelloParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.pathName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPathName([NotNull] HelloParser.PathNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.pathName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPathName([NotNull] HelloParser.PathNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.timeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeExpression([NotNull] HelloParser.TimeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.timeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeExpression([NotNull] HelloParser.TimeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.actualParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActualParameterList([NotNull] HelloParser.ActualParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.actualParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActualParameterList([NotNull] HelloParser.ActualParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOperator([NotNull] HelloParser.LogicalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOperator([NotNull] HelloParser.LogicalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.collectionKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionKind([NotNull] HelloParser.CollectionKindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.collectionKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionKind([NotNull] HelloParser.CollectionKindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalOperator([NotNull] HelloParser.RelationalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalOperator([NotNull] HelloParser.RelationalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOperator([NotNull] HelloParser.AddOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOperator([NotNull] HelloParser.AddOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.multiplyOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyOperator([NotNull] HelloParser.MultiplyOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.multiplyOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyOperator([NotNull] HelloParser.MultiplyOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] HelloParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] HelloParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] HelloParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] HelloParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HelloParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] HelloParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HelloParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] HelloParser.NumberContext context);
}
