//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hello.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class HelloParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, Stereotype=45, 
		NAME=46, NUMBER=47, WS=48;
	public const int
		RULE_oclFile = 0, RULE_packageName = 1, RULE_oclExpressions = 2, RULE_constraint = 3, 
		RULE_contextDeclaration = 4, RULE_classifierContext = 5, RULE_operationContext = 6, 
		RULE_operationName = 7, RULE_formalParameterList = 8, RULE_typeSpecifier = 9, 
		RULE_collectionType = 10, RULE_oclExpression = 11, RULE_returnType = 12, 
		RULE_expression = 13, RULE_letExpression = 14, RULE_ifExpression = 15, 
		RULE_implExpression = 16, RULE_orExpression = 17, RULE_andExpression = 18, 
		RULE_relationalExpression = 19, RULE_additiveExpression = 20, RULE_multiplicativeExpression = 21, 
		RULE_unaryExpression = 22, RULE_postfixExpression = 23, RULE_primaryExpression = 24, 
		RULE_propertyCallParameters = 25, RULE_literal = 26, RULE_stringLiteral = 27, 
		RULE_enumLiteral = 28, RULE_simpleTypeSpecifier = 29, RULE_literalCollection = 30, 
		RULE_collectionItem = 31, RULE_propertyCall = 32, RULE_qualifiers = 33, 
		RULE_declarator = 34, RULE_pathName = 35, RULE_timeExpression = 36, RULE_actualParameterList = 37, 
		RULE_logicalOperator = 38, RULE_collectionKind = 39, RULE_relationalOperator = 40, 
		RULE_addOperator = 41, RULE_multiplyOperator = 42, RULE_unaryOperator = 43;
	public static readonly string[] ruleNames = {
		"oclFile", "packageName", "oclExpressions", "constraint", "contextDeclaration", 
		"classifierContext", "operationContext", "operationName", "formalParameterList", 
		"typeSpecifier", "collectionType", "oclExpression", "returnType", "expression", 
		"letExpression", "ifExpression", "implExpression", "orExpression", "andExpression", 
		"relationalExpression", "additiveExpression", "multiplicativeExpression", 
		"unaryExpression", "postfixExpression", "primaryExpression", "propertyCallParameters", 
		"literal", "stringLiteral", "enumLiteral", "simpleTypeSpecifier", "literalCollection", 
		"collectionItem", "propertyCall", "qualifiers", "declarator", "pathName", 
		"timeExpression", "actualParameterList", "logicalOperator", "collectionKind", 
		"relationalOperator", "addOperator", "multiplyOperator", "unaryOperator"
	};

	private static readonly string[] _LiteralNames = {
		null, "'package'", "'endpackage'", "'@'", "':'", "'context'", "'::'", 
		"'('", "')'", "'='", "'+'", "'-'", "'<'", "'<='", "'>='", "'>'", "'/'", 
		"'*'", "'<>'", "'implies'", "'not'", "'or'", "'xor'", "'and'", "','", 
		"'let'", "';'", "'if'", "'then'", "'else'", "'endif'", "'.'", "'->'", 
		"'\"'", "'{'", "'}'", "'..'", "'['", "']'", "'|'", "'pre'", "'Set'", "'Bag'", 
		"'Sequence'", "'Collection'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "Stereotype", "NAME", 
		"NUMBER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Hello.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static HelloParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public HelloParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public HelloParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class OclFileContext : ParserRuleContext {
		public PackageNameContext[] packageName() {
			return GetRuleContexts<PackageNameContext>();
		}
		public PackageNameContext packageName(int i) {
			return GetRuleContext<PackageNameContext>(i);
		}
		public OclExpressionsContext[] oclExpressions() {
			return GetRuleContexts<OclExpressionsContext>();
		}
		public OclExpressionsContext oclExpressions(int i) {
			return GetRuleContext<OclExpressionsContext>(i);
		}
		public OclFileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oclFile; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOclFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OclFileContext oclFile() {
		OclFileContext _localctx = new OclFileContext(Context, State);
		EnterRule(_localctx, 0, RULE_oclFile);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 88; Match(T__0);
				State = 89; packageName();
				State = 90; oclExpressions();
				State = 91; Match(T__1);
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__0 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PackageNameContext : ParserRuleContext {
		public PathNameContext pathName() {
			return GetRuleContext<PathNameContext>(0);
		}
		public PackageNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_packageName; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPackageName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PackageNameContext packageName() {
		PackageNameContext _localctx = new PackageNameContext(Context, State);
		EnterRule(_localctx, 2, RULE_packageName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97; pathName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OclExpressionsContext : ParserRuleContext {
		public ConstraintContext[] constraint() {
			return GetRuleContexts<ConstraintContext>();
		}
		public ConstraintContext constraint(int i) {
			return GetRuleContext<ConstraintContext>(i);
		}
		public OclExpressionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oclExpressions; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOclExpressions(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OclExpressionsContext oclExpressions() {
		OclExpressionsContext _localctx = new OclExpressionsContext(Context, State);
		EnterRule(_localctx, 4, RULE_oclExpressions);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 99; constraint();
				}
				}
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstraintContext : ParserRuleContext {
		public ContextDeclarationContext contextDeclaration() {
			return GetRuleContext<ContextDeclarationContext>(0);
		}
		public ITerminalNode[] Stereotype() { return GetTokens(HelloParser.Stereotype); }
		public ITerminalNode Stereotype(int i) {
			return GetToken(HelloParser.Stereotype, i);
		}
		public ITerminalNode[] NUMBER() { return GetTokens(HelloParser.NUMBER); }
		public ITerminalNode NUMBER(int i) {
			return GetToken(HelloParser.NUMBER, i);
		}
		public OclExpressionContext[] oclExpression() {
			return GetRuleContexts<OclExpressionContext>();
		}
		public OclExpressionContext oclExpression(int i) {
			return GetRuleContext<OclExpressionContext>(i);
		}
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public ConstraintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constraint; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstraint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstraintContext constraint() {
		ConstraintContext _localctx = new ConstraintContext(Context, State);
		EnterRule(_localctx, 6, RULE_constraint);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105; contextDeclaration();
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 106; Match(Stereotype);
				State = 107; Match(T__2);
				State = 108; Match(NUMBER);
				State = 110;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NAME) {
					{
					State = 109; Match(NAME);
					}
				}

				State = 112; Match(T__3);
				State = 113; oclExpression();
				}
				}
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Stereotype );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContextDeclarationContext : ParserRuleContext {
		public OperationContextContext operationContext() {
			return GetRuleContext<OperationContextContext>(0);
		}
		public ClassifierContextContext classifierContext() {
			return GetRuleContext<ClassifierContextContext>(0);
		}
		public ContextDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_contextDeclaration; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContextDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContextDeclarationContext contextDeclaration() {
		ContextDeclarationContext _localctx = new ContextDeclarationContext(Context, State);
		EnterRule(_localctx, 8, RULE_contextDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118; Match(T__4);
			State = 121;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				State = 119; operationContext();
				}
				break;
			case 2:
				{
				State = 120; classifierContext();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassifierContextContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public ClassifierContextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classifierContext; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassifierContext(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassifierContextContext classifierContext() {
		ClassifierContextContext _localctx = new ClassifierContextContext(Context, State);
		EnterRule(_localctx, 10, RULE_classifierContext);
		try {
			State = 127;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 123; Match(NAME);
				State = 124; Match(T__3);
				State = 125; Match(NAME);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 126; Match(NAME);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContextContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public OperationNameContext operationName() {
			return GetRuleContext<OperationNameContext>(0);
		}
		public FormalParameterListContext formalParameterList() {
			return GetRuleContext<FormalParameterListContext>(0);
		}
		public ReturnTypeContext returnType() {
			return GetRuleContext<ReturnTypeContext>(0);
		}
		public OperationContextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operationContext; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperationContext(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationContextContext operationContext() {
		OperationContextContext _localctx = new OperationContextContext(Context, State);
		EnterRule(_localctx, 12, RULE_operationContext);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129; Match(NAME);
			State = 130; Match(T__5);
			State = 131; operationName();
			State = 132; Match(T__6);
			State = 133; formalParameterList();
			State = 134; Match(T__7);
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 135; Match(T__3);
				State = 136; returnType();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationNameContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public OperationNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operationName; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperationName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationNameContext operationName() {
		OperationNameContext _localctx = new OperationNameContext(Context, State);
		EnterRule(_localctx, 14, RULE_operationName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << T__20) | (1L << T__21) | (1L << T__22) | (1L << NAME))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormalParameterListContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public TypeSpecifierContext[] typeSpecifier() {
			return GetRuleContexts<TypeSpecifierContext>();
		}
		public TypeSpecifierContext typeSpecifier(int i) {
			return GetRuleContext<TypeSpecifierContext>(i);
		}
		public FormalParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formalParameterList; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormalParameterList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalParameterListContext formalParameterList() {
		FormalParameterListContext _localctx = new FormalParameterListContext(Context, State);
		EnterRule(_localctx, 16, RULE_formalParameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NAME) {
				{
				State = 141; Match(NAME);
				State = 142; Match(T__3);
				State = 143; typeSpecifier();
				State = 150;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__23) {
					{
					{
					State = 144; Match(T__23);
					State = 145; Match(NAME);
					State = 146; Match(T__3);
					State = 147; typeSpecifier();
					}
					}
					State = 152;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeSpecifierContext : ParserRuleContext {
		public SimpleTypeSpecifierContext simpleTypeSpecifier() {
			return GetRuleContext<SimpleTypeSpecifierContext>(0);
		}
		public CollectionTypeContext collectionType() {
			return GetRuleContext<CollectionTypeContext>(0);
		}
		public TypeSpecifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeSpecifier; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeSpecifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeSpecifierContext typeSpecifier() {
		TypeSpecifierContext _localctx = new TypeSpecifierContext(Context, State);
		EnterRule(_localctx, 18, RULE_typeSpecifier);
		try {
			State = 157;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NAME:
				EnterOuterAlt(_localctx, 1);
				{
				State = 155; simpleTypeSpecifier();
				}
				break;
			case T__40:
			case T__41:
			case T__42:
			case T__43:
				EnterOuterAlt(_localctx, 2);
				{
				State = 156; collectionType();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionTypeContext : ParserRuleContext {
		public CollectionKindContext collectionKind() {
			return GetRuleContext<CollectionKindContext>(0);
		}
		public SimpleTypeSpecifierContext simpleTypeSpecifier() {
			return GetRuleContext<SimpleTypeSpecifierContext>(0);
		}
		public CollectionTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionType; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCollectionType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CollectionTypeContext collectionType() {
		CollectionTypeContext _localctx = new CollectionTypeContext(Context, State);
		EnterRule(_localctx, 20, RULE_collectionType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159; collectionKind();
			State = 160; Match(T__6);
			State = 161; simpleTypeSpecifier();
			State = 162; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OclExpressionContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LetExpressionContext[] letExpression() {
			return GetRuleContexts<LetExpressionContext>();
		}
		public LetExpressionContext letExpression(int i) {
			return GetRuleContext<LetExpressionContext>(i);
		}
		public OclExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oclExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOclExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OclExpressionContext oclExpression() {
		OclExpressionContext _localctx = new OclExpressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_oclExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__24) {
				{
				{
				State = 164; letExpression();
				}
				}
				State = 169;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 170; expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnTypeContext : ParserRuleContext {
		public TypeSpecifierContext typeSpecifier() {
			return GetRuleContext<TypeSpecifierContext>(0);
		}
		public ReturnTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnType; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnTypeContext returnType() {
		ReturnTypeContext _localctx = new ReturnTypeContext(Context, State);
		EnterRule(_localctx, 24, RULE_returnType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 172; typeSpecifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ImplExpressionContext implExpression() {
			return GetRuleContext<ImplExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 26, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174; implExpression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LetExpressionContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public FormalParameterListContext formalParameterList() {
			return GetRuleContext<FormalParameterListContext>(0);
		}
		public TypeSpecifierContext typeSpecifier() {
			return GetRuleContext<TypeSpecifierContext>(0);
		}
		public LetExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetExpressionContext letExpression() {
		LetExpressionContext _localctx = new LetExpressionContext(Context, State);
		EnterRule(_localctx, 28, RULE_letExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176; Match(T__24);
			State = 177; Match(NAME);
			State = 182;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 178; Match(T__6);
				State = 179; formalParameterList();
				State = 180; Match(T__7);
				}
			}

			State = 186;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 184; Match(T__3);
				State = 185; typeSpecifier();
				}
			}

			State = 188; Match(T__8);
			State = 189; expression();
			State = 190; Match(T__25);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfExpressionContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public IfExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfExpressionContext ifExpression() {
		IfExpressionContext _localctx = new IfExpressionContext(Context, State);
		EnterRule(_localctx, 30, RULE_ifExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192; Match(T__26);
			State = 193; expression();
			State = 194; Match(T__27);
			State = 195; expression();
			State = 196; Match(T__28);
			State = 197; expression();
			State = 198; Match(T__29);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImplExpressionContext : ParserRuleContext {
		public OrExpressionContext[] orExpression() {
			return GetRuleContexts<OrExpressionContext>();
		}
		public OrExpressionContext orExpression(int i) {
			return GetRuleContext<OrExpressionContext>(i);
		}
		public ImplExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_implExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImplExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImplExpressionContext implExpression() {
		ImplExpressionContext _localctx = new ImplExpressionContext(Context, State);
		EnterRule(_localctx, 32, RULE_implExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200; orExpression();
			State = 205;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__18) {
				{
				{
				State = 201; Match(T__18);
				State = 202; orExpression();
				}
				}
				State = 207;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrExpressionContext : ParserRuleContext {
		public AndExpressionContext[] andExpression() {
			return GetRuleContexts<AndExpressionContext>();
		}
		public AndExpressionContext andExpression(int i) {
			return GetRuleContext<AndExpressionContext>(i);
		}
		public OrExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrExpressionContext orExpression() {
		OrExpressionContext _localctx = new OrExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_orExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208; andExpression();
			State = 213;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__20 || _la==T__21) {
				{
				{
				State = 209;
				_la = TokenStream.LA(1);
				if ( !(_la==T__20 || _la==T__21) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 210; andExpression();
				}
				}
				State = 215;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AndExpressionContext : ParserRuleContext {
		public RelationalExpressionContext[] relationalExpression() {
			return GetRuleContexts<RelationalExpressionContext>();
		}
		public RelationalExpressionContext relationalExpression(int i) {
			return GetRuleContext<RelationalExpressionContext>(i);
		}
		public AndExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_andExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AndExpressionContext andExpression() {
		AndExpressionContext _localctx = new AndExpressionContext(Context, State);
		EnterRule(_localctx, 36, RULE_andExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 216; relationalExpression();
			State = 221;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__22) {
				{
				{
				State = 217; Match(T__22);
				State = 218; relationalExpression();
				}
				}
				State = 223;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationalExpressionContext : ParserRuleContext {
		public AdditiveExpressionContext[] additiveExpression() {
			return GetRuleContexts<AdditiveExpressionContext>();
		}
		public AdditiveExpressionContext additiveExpression(int i) {
			return GetRuleContext<AdditiveExpressionContext>(i);
		}
		public RelationalOperatorContext relationalOperator() {
			return GetRuleContext<RelationalOperatorContext>(0);
		}
		public RelationalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationalExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalExpressionContext relationalExpression() {
		RelationalExpressionContext _localctx = new RelationalExpressionContext(Context, State);
		EnterRule(_localctx, 38, RULE_relationalExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 224; additiveExpression();
			State = 228;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__17))) != 0)) {
				{
				State = 225; relationalOperator();
				State = 226; additiveExpression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AdditiveExpressionContext : ParserRuleContext {
		public MultiplicativeExpressionContext[] multiplicativeExpression() {
			return GetRuleContexts<MultiplicativeExpressionContext>();
		}
		public MultiplicativeExpressionContext multiplicativeExpression(int i) {
			return GetRuleContext<MultiplicativeExpressionContext>(i);
		}
		public AddOperatorContext[] addOperator() {
			return GetRuleContexts<AddOperatorContext>();
		}
		public AddOperatorContext addOperator(int i) {
			return GetRuleContext<AddOperatorContext>(i);
		}
		public AdditiveExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additiveExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditiveExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AdditiveExpressionContext additiveExpression() {
		AdditiveExpressionContext _localctx = new AdditiveExpressionContext(Context, State);
		EnterRule(_localctx, 40, RULE_additiveExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230; multiplicativeExpression();
			State = 236;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__9 || _la==T__10) {
				{
				{
				State = 231; addOperator();
				State = 232; multiplicativeExpression();
				}
				}
				State = 238;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiplicativeExpressionContext : ParserRuleContext {
		public UnaryExpressionContext[] unaryExpression() {
			return GetRuleContexts<UnaryExpressionContext>();
		}
		public UnaryExpressionContext unaryExpression(int i) {
			return GetRuleContext<UnaryExpressionContext>(i);
		}
		public MultiplyOperatorContext[] multiplyOperator() {
			return GetRuleContexts<MultiplyOperatorContext>();
		}
		public MultiplyOperatorContext multiplyOperator(int i) {
			return GetRuleContext<MultiplyOperatorContext>(i);
		}
		public MultiplicativeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplicativeExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicativeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplicativeExpressionContext multiplicativeExpression() {
		MultiplicativeExpressionContext _localctx = new MultiplicativeExpressionContext(Context, State);
		EnterRule(_localctx, 42, RULE_multiplicativeExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 239; unaryExpression();
			State = 245;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__15 || _la==T__16) {
				{
				{
				State = 240; multiplyOperator();
				State = 241; unaryExpression();
				}
				}
				State = 247;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		public UnaryOperatorContext unaryOperator() {
			return GetRuleContext<UnaryOperatorContext>(0);
		}
		public PostfixExpressionContext postfixExpression() {
			return GetRuleContext<PostfixExpressionContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 44, RULE_unaryExpression);
		try {
			State = 252;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__10:
			case T__19:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 248; unaryOperator();
				State = 249; postfixExpression();
				}
				}
				break;
			case T__6:
			case T__26:
			case T__32:
			case T__40:
			case T__41:
			case T__42:
			case T__43:
			case NAME:
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 251; postfixExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PostfixExpressionContext : ParserRuleContext {
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public PropertyCallContext[] propertyCall() {
			return GetRuleContexts<PropertyCallContext>();
		}
		public PropertyCallContext propertyCall(int i) {
			return GetRuleContext<PropertyCallContext>(i);
		}
		public PostfixExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postfixExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPostfixExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PostfixExpressionContext postfixExpression() {
		PostfixExpressionContext _localctx = new PostfixExpressionContext(Context, State);
		EnterRule(_localctx, 46, RULE_postfixExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 254; primaryExpression();
			State = 259;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__30 || _la==T__31) {
				{
				{
				State = 255;
				_la = TokenStream.LA(1);
				if ( !(_la==T__30 || _la==T__31) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 256; propertyCall();
				}
				}
				State = 261;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryExpressionContext : ParserRuleContext {
		public LiteralCollectionContext literalCollection() {
			return GetRuleContext<LiteralCollectionContext>(0);
		}
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public PropertyCallContext propertyCall() {
			return GetRuleContext<PropertyCallContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public IfExpressionContext ifExpression() {
			return GetRuleContext<IfExpressionContext>(0);
		}
		public PrimaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primaryExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryExpressionContext primaryExpression() {
		PrimaryExpressionContext _localctx = new PrimaryExpressionContext(Context, State);
		EnterRule(_localctx, 48, RULE_primaryExpression);
		try {
			State = 270;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 262; literalCollection();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 263; literal();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 264; propertyCall();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 265; Match(T__6);
				State = 266; expression();
				State = 267; Match(T__7);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 269; ifExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyCallParametersContext : ParserRuleContext {
		public DeclaratorContext declarator() {
			return GetRuleContext<DeclaratorContext>(0);
		}
		public ActualParameterListContext actualParameterList() {
			return GetRuleContext<ActualParameterListContext>(0);
		}
		public PropertyCallParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyCallParameters; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyCallParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyCallParametersContext propertyCallParameters() {
		PropertyCallParametersContext _localctx = new PropertyCallParametersContext(Context, State);
		EnterRule(_localctx, 50, RULE_propertyCallParameters);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 272; Match(T__6);
			State = 274;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				{
				State = 273; declarator();
				}
				break;
			}
			State = 277;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__6) | (1L << T__10) | (1L << T__19) | (1L << T__26) | (1L << T__32) | (1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << T__43) | (1L << NAME) | (1L << NUMBER))) != 0)) {
				{
				State = 276; actualParameterList();
				}
			}

			State = 279; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode NUMBER() { return GetToken(HelloParser.NUMBER, 0); }
		public EnumLiteralContext enumLiteral() {
			return GetRuleContext<EnumLiteralContext>(0);
		}
		public StringLiteralContext stringLiteral() {
			return GetRuleContext<StringLiteralContext>(0);
		}
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 52, RULE_literal);
		try {
			State = 284;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 281; Match(NUMBER);
				}
				break;
			case NAME:
				EnterOuterAlt(_localctx, 2);
				{
				State = 282; enumLiteral();
				}
				break;
			case T__32:
				EnterOuterAlt(_localctx, 3);
				{
				State = 283; stringLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringLiteralContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public StringLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringLiteral; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringLiteralContext stringLiteral() {
		StringLiteralContext _localctx = new StringLiteralContext(Context, State);
		EnterRule(_localctx, 54, RULE_stringLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 286; Match(T__32);
			State = 287; Match(NAME);
			State = 288; Match(T__32);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumLiteralContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public EnumLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumLiteral; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumLiteralContext enumLiteral() {
		EnumLiteralContext _localctx = new EnumLiteralContext(Context, State);
		EnterRule(_localctx, 56, RULE_enumLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 290; Match(NAME);
			State = 291; Match(T__5);
			State = 292; Match(NAME);
			State = 297;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 293; Match(T__5);
				State = 294; Match(NAME);
				}
				}
				State = 299;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleTypeSpecifierContext : ParserRuleContext {
		public PathNameContext pathName() {
			return GetRuleContext<PathNameContext>(0);
		}
		public SimpleTypeSpecifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleTypeSpecifier; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimpleTypeSpecifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SimpleTypeSpecifierContext simpleTypeSpecifier() {
		SimpleTypeSpecifierContext _localctx = new SimpleTypeSpecifierContext(Context, State);
		EnterRule(_localctx, 58, RULE_simpleTypeSpecifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 300; pathName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralCollectionContext : ParserRuleContext {
		public CollectionKindContext collectionKind() {
			return GetRuleContext<CollectionKindContext>(0);
		}
		public CollectionItemContext[] collectionItem() {
			return GetRuleContexts<CollectionItemContext>();
		}
		public CollectionItemContext collectionItem(int i) {
			return GetRuleContext<CollectionItemContext>(i);
		}
		public LiteralCollectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literalCollection; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteralCollection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralCollectionContext literalCollection() {
		LiteralCollectionContext _localctx = new LiteralCollectionContext(Context, State);
		EnterRule(_localctx, 60, RULE_literalCollection);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 302; collectionKind();
			State = 303; Match(T__33);
			State = 312;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__6) | (1L << T__10) | (1L << T__19) | (1L << T__26) | (1L << T__32) | (1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << T__43) | (1L << NAME) | (1L << NUMBER))) != 0)) {
				{
				State = 304; collectionItem();
				State = 309;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__23) {
					{
					{
					State = 305; Match(T__23);
					State = 306; collectionItem();
					}
					}
					State = 311;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 314; Match(T__34);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionItemContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public CollectionItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionItem; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCollectionItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CollectionItemContext collectionItem() {
		CollectionItemContext _localctx = new CollectionItemContext(Context, State);
		EnterRule(_localctx, 62, RULE_collectionItem);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 316; expression();
			State = 319;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__35) {
				{
				State = 317; Match(T__35);
				State = 318; expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyCallContext : ParserRuleContext {
		public PathNameContext pathName() {
			return GetRuleContext<PathNameContext>(0);
		}
		public ITerminalNode NUMBER() { return GetToken(HelloParser.NUMBER, 0); }
		public TimeExpressionContext timeExpression() {
			return GetRuleContext<TimeExpressionContext>(0);
		}
		public QualifiersContext qualifiers() {
			return GetRuleContext<QualifiersContext>(0);
		}
		public PropertyCallParametersContext propertyCallParameters() {
			return GetRuleContext<PropertyCallParametersContext>(0);
		}
		public PropertyCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyCall; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyCallContext propertyCall() {
		PropertyCallContext _localctx = new PropertyCallContext(Context, State);
		EnterRule(_localctx, 64, RULE_propertyCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 321; pathName();
			State = 324;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				{
				State = 322; Match(T__2);
				State = 323; Match(NUMBER);
				}
				break;
			}
			State = 327;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 326; timeExpression();
				}
			}

			State = 330;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__36) {
				{
				State = 329; qualifiers();
				}
			}

			State = 333;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 332; propertyCallParameters();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiersContext : ParserRuleContext {
		public ActualParameterListContext actualParameterList() {
			return GetRuleContext<ActualParameterListContext>(0);
		}
		public QualifiersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiers; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualifiers(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QualifiersContext qualifiers() {
		QualifiersContext _localctx = new QualifiersContext(Context, State);
		EnterRule(_localctx, 66, RULE_qualifiers);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 335; Match(T__36);
			State = 336; actualParameterList();
			State = 337; Match(T__37);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclaratorContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public SimpleTypeSpecifierContext simpleTypeSpecifier() {
			return GetRuleContext<SimpleTypeSpecifierContext>(0);
		}
		public TypeSpecifierContext typeSpecifier() {
			return GetRuleContext<TypeSpecifierContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public DeclaratorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declarator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclarator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclaratorContext declarator() {
		DeclaratorContext _localctx = new DeclaratorContext(Context, State);
		EnterRule(_localctx, 68, RULE_declarator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 339; Match(NAME);
			State = 344;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__23) {
				{
				{
				State = 340; Match(T__23);
				State = 341; Match(NAME);
				}
				}
				State = 346;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 349;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 347; Match(T__3);
				State = 348; simpleTypeSpecifier();
				}
			}

			State = 358;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__25) {
				{
				State = 351; Match(T__25);
				State = 352; Match(NAME);
				State = 353; Match(T__3);
				State = 354; typeSpecifier();
				State = 355; Match(T__8);
				State = 356; expression();
				}
			}

			State = 360; Match(T__38);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PathNameContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public PathNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pathName; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPathName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PathNameContext pathName() {
		PathNameContext _localctx = new PathNameContext(Context, State);
		EnterRule(_localctx, 70, RULE_pathName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 362; Match(NAME);
			State = 367;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 363; Match(T__5);
				State = 364; Match(NAME);
				}
				}
				State = 369;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeExpressionContext : ParserRuleContext {
		public TimeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeExpressionContext timeExpression() {
		TimeExpressionContext _localctx = new TimeExpressionContext(Context, State);
		EnterRule(_localctx, 72, RULE_timeExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 370; Match(T__2);
			State = 371; Match(T__39);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActualParameterListContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ActualParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actualParameterList; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActualParameterList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActualParameterListContext actualParameterList() {
		ActualParameterListContext _localctx = new ActualParameterListContext(Context, State);
		EnterRule(_localctx, 74, RULE_actualParameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 373; expression();
			State = 378;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__23) {
				{
				{
				State = 374; Match(T__23);
				State = 375; expression();
				}
				}
				State = 380;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOperatorContext : ParserRuleContext {
		public LogicalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalOperatorContext logicalOperator() {
		LogicalOperatorContext _localctx = new LogicalOperatorContext(Context, State);
		EnterRule(_localctx, 76, RULE_logicalOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 381;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__18) | (1L << T__20) | (1L << T__21) | (1L << T__22))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionKindContext : ParserRuleContext {
		public CollectionKindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionKind; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCollectionKind(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CollectionKindContext collectionKind() {
		CollectionKindContext _localctx = new CollectionKindContext(Context, State);
		EnterRule(_localctx, 78, RULE_collectionKind);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 383;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << T__43))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationalOperatorContext : ParserRuleContext {
		public RelationalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationalOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalOperatorContext relationalOperator() {
		RelationalOperatorContext _localctx = new RelationalOperatorContext(Context, State);
		EnterRule(_localctx, 80, RULE_relationalOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 385;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__17))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddOperatorContext : ParserRuleContext {
		public AddOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddOperatorContext addOperator() {
		AddOperatorContext _localctx = new AddOperatorContext(Context, State);
		EnterRule(_localctx, 82, RULE_addOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 387;
			_la = TokenStream.LA(1);
			if ( !(_la==T__9 || _la==T__10) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiplyOperatorContext : ParserRuleContext {
		public MultiplyOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplyOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplyOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplyOperatorContext multiplyOperator() {
		MultiplyOperatorContext _localctx = new MultiplyOperatorContext(Context, State);
		EnterRule(_localctx, 84, RULE_multiplyOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 389;
			_la = TokenStream.LA(1);
			if ( !(_la==T__15 || _la==T__16) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryOperatorContext : ParserRuleContext {
		public UnaryOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryOperatorContext unaryOperator() {
		UnaryOperatorContext _localctx = new UnaryOperatorContext(Context, State);
		EnterRule(_localctx, 86, RULE_unaryOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 391;
			_la = TokenStream.LA(1);
			if ( !(_la==T__10 || _la==T__19) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x32', '\x18C', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x4', '+', '\t', '+', '\x4', ',', '\t', 
		',', '\x4', '-', '\t', '-', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x6', '\x2', '`', '\n', '\x2', '\r', '\x2', 
		'\xE', '\x2', '\x61', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\a', 
		'\x4', 'g', '\n', '\x4', '\f', '\x4', '\xE', '\x4', 'j', '\v', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x5', '\x5', 'q', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x6', '\x5', 
		'u', '\n', '\x5', '\r', '\x5', '\xE', '\x5', 'v', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x5', '\x6', '|', '\n', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x82', '\n', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x5', '\b', '\x8C', '\n', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\a', '\n', '\x97', '\n', '\n', '\f', 
		'\n', '\xE', '\n', '\x9A', '\v', '\n', '\x5', '\n', '\x9C', '\n', '\n', 
		'\x3', '\v', '\x3', '\v', '\x5', '\v', '\xA0', '\n', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\a', 
		'\r', '\xA8', '\n', '\r', '\f', '\r', '\xE', '\r', '\xAB', '\v', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x5', '\x10', '\xB9', '\n', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x5', '\x10', '\xBD', '\n', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\xCE', 
		'\n', '\x12', '\f', '\x12', '\xE', '\x12', '\xD1', '\v', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xD6', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xD9', '\v', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\a', '\x14', '\xDE', '\n', '\x14', '\f', '\x14', 
		'\xE', '\x14', '\xE1', '\v', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x5', '\x15', '\xE7', '\n', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\xED', '\n', 
		'\x16', '\f', '\x16', '\xE', '\x16', '\xF0', '\v', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\xF6', '\n', 
		'\x17', '\f', '\x17', '\xE', '\x17', '\xF9', '\v', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xFF', '\n', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\a', '\x19', '\x104', 
		'\n', '\x19', '\f', '\x19', '\xE', '\x19', '\x107', '\v', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\x111', '\n', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', '\x115', '\n', '\x1B', '\x3', 
		'\x1B', '\x5', '\x1B', '\x118', '\n', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x5', '\x1C', '\x11F', '\n', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\a', 
		'\x1E', '\x12A', '\n', '\x1E', '\f', '\x1E', '\xE', '\x1E', '\x12D', '\v', 
		'\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\a', ' ', '\x136', '\n', ' ', '\f', ' ', '\xE', 
		' ', '\x139', '\v', ' ', '\x5', ' ', '\x13B', '\n', ' ', '\x3', ' ', '\x3', 
		' ', '\x3', '!', '\x3', '!', '\x3', '!', '\x5', '!', '\x142', '\n', '!', 
		'\x3', '\"', '\x3', '\"', '\x3', '\"', '\x5', '\"', '\x147', '\n', '\"', 
		'\x3', '\"', '\x5', '\"', '\x14A', '\n', '\"', '\x3', '\"', '\x5', '\"', 
		'\x14D', '\n', '\"', '\x3', '\"', '\x5', '\"', '\x150', '\n', '\"', '\x3', 
		'#', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', 
		'$', '\a', '$', '\x159', '\n', '$', '\f', '$', '\xE', '$', '\x15C', '\v', 
		'$', '\x3', '$', '\x3', '$', '\x5', '$', '\x160', '\n', '$', '\x3', '$', 
		'\x3', '$', '\x3', '$', '\x3', '$', '\x3', '$', '\x3', '$', '\x3', '$', 
		'\x5', '$', '\x169', '\n', '$', '\x3', '$', '\x3', '$', '\x3', '%', '\x3', 
		'%', '\x3', '%', '\a', '%', '\x170', '\n', '%', '\f', '%', '\xE', '%', 
		'\x173', '\v', '%', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', '\'', '\x3', 
		'\'', '\x3', '\'', '\a', '\'', '\x17B', '\n', '\'', '\f', '\'', '\xE', 
		'\'', '\x17E', '\v', '\'', '\x3', '(', '\x3', '(', '\x3', ')', '\x3', 
		')', '\x3', '*', '\x3', '*', '\x3', '+', '\x3', '+', '\x3', ',', '\x3', 
		',', '\x3', '-', '\x3', '-', '\x3', '-', '\x2', '\x2', '.', '\x2', '\x4', 
		'\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', 
		'\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', 
		'\x32', '\x34', '\x36', '\x38', ':', '<', '>', '@', '\x42', '\x44', '\x46', 
		'H', 'J', 'L', 'N', 'P', 'R', 'T', 'V', 'X', '\x2', '\v', '\x4', '\x2', 
		'\v', '\x19', '\x30', '\x30', '\x3', '\x2', '\x17', '\x18', '\x3', '\x2', 
		'!', '\"', '\x4', '\x2', '\x15', '\x15', '\x17', '\x19', '\x3', '\x2', 
		'+', '.', '\x5', '\x2', '\v', '\v', '\xE', '\x11', '\x14', '\x14', '\x3', 
		'\x2', '\f', '\r', '\x3', '\x2', '\x12', '\x13', '\x4', '\x2', '\r', '\r', 
		'\x16', '\x16', '\x2', '\x189', '\x2', '_', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x63', '\x3', '\x2', '\x2', '\x2', '\x6', 'h', '\x3', '\x2', '\x2', 
		'\x2', '\b', 'k', '\x3', '\x2', '\x2', '\x2', '\n', 'x', '\x3', '\x2', 
		'\x2', '\x2', '\f', '\x81', '\x3', '\x2', '\x2', '\x2', '\xE', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x10', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x12', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x14', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x18', '\xA9', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\xB0', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\xC2', '\x3', '\x2', '\x2', '\x2', '\"', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '$', '\xD2', '\x3', '\x2', '\x2', '\x2', '&', '\xDA', 
		'\x3', '\x2', '\x2', '\x2', '(', '\xE2', '\x3', '\x2', '\x2', '\x2', '*', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', ',', '\xF1', '\x3', '\x2', '\x2', 
		'\x2', '.', '\xFE', '\x3', '\x2', '\x2', '\x2', '\x30', '\x100', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\x110', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x112', '\x3', '\x2', '\x2', '\x2', '\x36', '\x11E', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x120', '\x3', '\x2', '\x2', '\x2', ':', '\x124', '\x3', 
		'\x2', '\x2', '\x2', '<', '\x12E', '\x3', '\x2', '\x2', '\x2', '>', '\x130', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x13E', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '\x143', '\x3', '\x2', '\x2', '\x2', '\x44', '\x151', '\x3', '\x2', 
		'\x2', '\x2', '\x46', '\x155', '\x3', '\x2', '\x2', '\x2', 'H', '\x16C', 
		'\x3', '\x2', '\x2', '\x2', 'J', '\x174', '\x3', '\x2', '\x2', '\x2', 
		'L', '\x177', '\x3', '\x2', '\x2', '\x2', 'N', '\x17F', '\x3', '\x2', 
		'\x2', '\x2', 'P', '\x181', '\x3', '\x2', '\x2', '\x2', 'R', '\x183', 
		'\x3', '\x2', '\x2', '\x2', 'T', '\x185', '\x3', '\x2', '\x2', '\x2', 
		'V', '\x187', '\x3', '\x2', '\x2', '\x2', 'X', '\x189', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '[', '\a', '\x3', '\x2', '\x2', '[', '\\', '\x5', '\x4', 
		'\x3', '\x2', '\\', ']', '\x5', '\x6', '\x4', '\x2', ']', '^', '\a', '\x4', 
		'\x2', '\x2', '^', '`', '\x3', '\x2', '\x2', '\x2', '_', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x5', 'H', '%', '\x2', 
		'\x64', '\x5', '\x3', '\x2', '\x2', '\x2', '\x65', 'g', '\x5', '\b', '\x5', 
		'\x2', '\x66', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 'j', '\x3', '\x2', 
		'\x2', '\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', 
		'\x2', '\x2', '\x2', 'i', '\a', '\x3', '\x2', '\x2', '\x2', 'j', 'h', 
		'\x3', '\x2', '\x2', '\x2', 'k', 't', '\x5', '\n', '\x6', '\x2', 'l', 
		'm', '\a', '/', '\x2', '\x2', 'm', 'n', '\a', '\x5', '\x2', '\x2', 'n', 
		'p', '\a', '\x31', '\x2', '\x2', 'o', 'q', '\a', '\x30', '\x2', '\x2', 
		'p', 'o', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 
		'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x6', '\x2', '\x2', 
		's', 'u', '\x5', '\x18', '\r', '\x2', 't', 'l', '\x3', '\x2', '\x2', '\x2', 
		'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', '\x2', 
		'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'x', '{', '\a', '\a', '\x2', '\x2', 'y', '|', '\x5', '\xE', '\b', 
		'\x2', 'z', '|', '\x5', '\f', '\a', '\x2', '{', 'y', '\x3', '\x2', '\x2', 
		'\x2', '{', 'z', '\x3', '\x2', '\x2', '\x2', '|', '\v', '\x3', '\x2', 
		'\x2', '\x2', '}', '~', '\a', '\x30', '\x2', '\x2', '~', '\x7F', '\a', 
		'\x6', '\x2', '\x2', '\x7F', '\x82', '\a', '\x30', '\x2', '\x2', '\x80', 
		'\x82', '\a', '\x30', '\x2', '\x2', '\x81', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x84', '\a', '\x30', '\x2', '\x2', '\x84', 
		'\x85', '\a', '\b', '\x2', '\x2', '\x85', '\x86', '\x5', '\x10', '\t', 
		'\x2', '\x86', '\x87', '\a', '\t', '\x2', '\x2', '\x87', '\x88', '\x5', 
		'\x12', '\n', '\x2', '\x88', '\x8B', '\a', '\n', '\x2', '\x2', '\x89', 
		'\x8A', '\a', '\x6', '\x2', '\x2', '\x8A', '\x8C', '\x5', '\x1A', '\xE', 
		'\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\xF', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\t', '\x2', '\x2', '\x2', '\x8E', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\a', '\x30', '\x2', '\x2', '\x90', '\x91', '\a', 
		'\x6', '\x2', '\x2', '\x91', '\x98', '\x5', '\x14', '\v', '\x2', '\x92', 
		'\x93', '\a', '\x1A', '\x2', '\x2', '\x93', '\x94', '\a', '\x30', '\x2', 
		'\x2', '\x94', '\x95', '\a', '\x6', '\x2', '\x2', '\x95', '\x97', '\x5', 
		'\x14', '\v', '\x2', '\x96', '\x92', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x98', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x13', '\x3', '\x2', '\x2', '\x2', '\x9D', '\xA0', '\x5', 
		'<', '\x1F', '\x2', '\x9E', '\xA0', '\x5', '\x16', '\f', '\x2', '\x9F', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\x15', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x5', 
		'P', ')', '\x2', '\xA2', '\xA3', '\a', '\t', '\x2', '\x2', '\xA3', '\xA4', 
		'\x5', '<', '\x1F', '\x2', '\xA4', '\xA5', '\a', '\n', '\x2', '\x2', '\xA5', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA8', '\x5', '\x1E', '\x10', 
		'\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\x5', 
		'\x1C', '\xF', '\x2', '\xAD', '\x19', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAF', '\x5', '\x14', '\v', '\x2', '\xAF', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\xB0', '\xB1', '\x5', '\"', '\x12', '\x2', '\xB1', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', '\x1B', '\x2', '\x2', '\xB3', 
		'\xB8', '\a', '\x30', '\x2', '\x2', '\xB4', '\xB5', '\a', '\t', '\x2', 
		'\x2', '\xB5', '\xB6', '\x5', '\x12', '\n', '\x2', '\xB6', '\xB7', '\a', 
		'\n', '\x2', '\x2', '\xB7', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\a', 
		'\x6', '\x2', '\x2', '\xBB', '\xBD', '\x5', '\x14', '\v', '\x2', '\xBC', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xBD', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', 
		'\v', '\x2', '\x2', '\xBF', '\xC0', '\x5', '\x1C', '\xF', '\x2', '\xC0', 
		'\xC1', '\a', '\x1C', '\x2', '\x2', '\xC1', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\xC2', '\xC3', '\a', '\x1D', '\x2', '\x2', '\xC3', '\xC4', '\x5', 
		'\x1C', '\xF', '\x2', '\xC4', '\xC5', '\a', '\x1E', '\x2', '\x2', '\xC5', 
		'\xC6', '\x5', '\x1C', '\xF', '\x2', '\xC6', '\xC7', '\a', '\x1F', '\x2', 
		'\x2', '\xC7', '\xC8', '\x5', '\x1C', '\xF', '\x2', '\xC8', '\xC9', '\a', 
		' ', '\x2', '\x2', '\xC9', '!', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCF', 
		'\x5', '$', '\x13', '\x2', '\xCB', '\xCC', '\a', '\x15', '\x2', '\x2', 
		'\xCC', '\xCE', '\x5', '$', '\x13', '\x2', '\xCD', '\xCB', '\x3', '\x2', 
		'\x2', '\x2', '\xCE', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', '\x2', 
		'\xD0', '#', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCF', '\x3', '\x2', 
		'\x2', '\x2', '\xD2', '\xD7', '\x5', '&', '\x14', '\x2', '\xD3', '\xD4', 
		'\t', '\x3', '\x2', '\x2', '\xD4', '\xD6', '\x5', '&', '\x14', '\x2', 
		'\xD5', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\xD7', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', 
		'\x3', '\x2', '\x2', '\x2', '\xD8', '%', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\xD7', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDF', '\x5', '(', '\x15', 
		'\x2', '\xDB', '\xDC', '\a', '\x19', '\x2', '\x2', '\xDC', '\xDE', '\x5', 
		'(', '\x15', '\x2', '\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xDF', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE2', 
		'\xE6', '\x5', '*', '\x16', '\x2', '\xE3', '\xE4', '\x5', 'R', '*', '\x2', 
		'\xE4', '\xE5', '\x5', '*', '\x16', '\x2', '\xE5', '\xE7', '\x3', '\x2', 
		'\x2', '\x2', '\xE6', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', 
		'\x3', '\x2', '\x2', '\x2', '\xE7', ')', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xEE', '\x5', ',', '\x17', '\x2', '\xE9', '\xEA', '\x5', 'T', '+', '\x2', 
		'\xEA', '\xEB', '\x5', ',', '\x17', '\x2', '\xEB', '\xED', '\x3', '\x2', 
		'\x2', '\x2', '\xEC', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xED', '\xF0', 
		'\x3', '\x2', '\x2', '\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', '\x2', 
		'\xEE', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xEF', '+', '\x3', '\x2', 
		'\x2', '\x2', '\xF0', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF7', 
		'\x5', '.', '\x18', '\x2', '\xF2', '\xF3', '\x5', 'V', ',', '\x2', '\xF3', 
		'\xF4', '\x5', '.', '\x18', '\x2', '\xF4', '\xF6', '\x3', '\x2', '\x2', 
		'\x2', '\xF5', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF9', '\x3', 
		'\x2', '\x2', '\x2', '\xF7', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF7', 
		'\xF8', '\x3', '\x2', '\x2', '\x2', '\xF8', '-', '\x3', '\x2', '\x2', 
		'\x2', '\xF9', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xFB', '\x5', 
		'X', '-', '\x2', '\xFB', '\xFC', '\x5', '\x30', '\x19', '\x2', '\xFC', 
		'\xFF', '\x3', '\x2', '\x2', '\x2', '\xFD', '\xFF', '\x5', '\x30', '\x19', 
		'\x2', '\xFE', '\xFA', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFD', '\x3', 
		'\x2', '\x2', '\x2', '\xFF', '/', '\x3', '\x2', '\x2', '\x2', '\x100', 
		'\x105', '\x5', '\x32', '\x1A', '\x2', '\x101', '\x102', '\t', '\x4', 
		'\x2', '\x2', '\x102', '\x104', '\x5', '\x42', '\"', '\x2', '\x103', '\x101', 
		'\x3', '\x2', '\x2', '\x2', '\x104', '\x107', '\x3', '\x2', '\x2', '\x2', 
		'\x105', '\x103', '\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\x3', 
		'\x2', '\x2', '\x2', '\x106', '\x31', '\x3', '\x2', '\x2', '\x2', '\x107', 
		'\x105', '\x3', '\x2', '\x2', '\x2', '\x108', '\x111', '\x5', '>', ' ', 
		'\x2', '\x109', '\x111', '\x5', '\x36', '\x1C', '\x2', '\x10A', '\x111', 
		'\x5', '\x42', '\"', '\x2', '\x10B', '\x10C', '\a', '\t', '\x2', '\x2', 
		'\x10C', '\x10D', '\x5', '\x1C', '\xF', '\x2', '\x10D', '\x10E', '\a', 
		'\n', '\x2', '\x2', '\x10E', '\x111', '\x3', '\x2', '\x2', '\x2', '\x10F', 
		'\x111', '\x5', ' ', '\x11', '\x2', '\x110', '\x108', '\x3', '\x2', '\x2', 
		'\x2', '\x110', '\x109', '\x3', '\x2', '\x2', '\x2', '\x110', '\x10A', 
		'\x3', '\x2', '\x2', '\x2', '\x110', '\x10B', '\x3', '\x2', '\x2', '\x2', 
		'\x110', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x111', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x112', '\x114', '\a', '\t', '\x2', '\x2', '\x113', 
		'\x115', '\x5', '\x46', '$', '\x2', '\x114', '\x113', '\x3', '\x2', '\x2', 
		'\x2', '\x114', '\x115', '\x3', '\x2', '\x2', '\x2', '\x115', '\x117', 
		'\x3', '\x2', '\x2', '\x2', '\x116', '\x118', '\x5', 'L', '\'', '\x2', 
		'\x117', '\x116', '\x3', '\x2', '\x2', '\x2', '\x117', '\x118', '\x3', 
		'\x2', '\x2', '\x2', '\x118', '\x119', '\x3', '\x2', '\x2', '\x2', '\x119', 
		'\x11A', '\a', '\n', '\x2', '\x2', '\x11A', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x11B', '\x11F', '\a', '\x31', '\x2', '\x2', '\x11C', '\x11F', 
		'\x5', ':', '\x1E', '\x2', '\x11D', '\x11F', '\x5', '\x38', '\x1D', '\x2', 
		'\x11E', '\x11B', '\x3', '\x2', '\x2', '\x2', '\x11E', '\x11C', '\x3', 
		'\x2', '\x2', '\x2', '\x11E', '\x11D', '\x3', '\x2', '\x2', '\x2', '\x11F', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x120', '\x121', '\a', '#', '\x2', 
		'\x2', '\x121', '\x122', '\a', '\x30', '\x2', '\x2', '\x122', '\x123', 
		'\a', '#', '\x2', '\x2', '\x123', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x124', '\x125', '\a', '\x30', '\x2', '\x2', '\x125', '\x126', '\a', 
		'\b', '\x2', '\x2', '\x126', '\x12B', '\a', '\x30', '\x2', '\x2', '\x127', 
		'\x128', '\a', '\b', '\x2', '\x2', '\x128', '\x12A', '\a', '\x30', '\x2', 
		'\x2', '\x129', '\x127', '\x3', '\x2', '\x2', '\x2', '\x12A', '\x12D', 
		'\x3', '\x2', '\x2', '\x2', '\x12B', '\x129', '\x3', '\x2', '\x2', '\x2', 
		'\x12B', '\x12C', '\x3', '\x2', '\x2', '\x2', '\x12C', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x12D', '\x12B', '\x3', '\x2', '\x2', '\x2', '\x12E', '\x12F', 
		'\x5', 'H', '%', '\x2', '\x12F', '=', '\x3', '\x2', '\x2', '\x2', '\x130', 
		'\x131', '\x5', 'P', ')', '\x2', '\x131', '\x13A', '\a', '$', '\x2', '\x2', 
		'\x132', '\x137', '\x5', '@', '!', '\x2', '\x133', '\x134', '\a', '\x1A', 
		'\x2', '\x2', '\x134', '\x136', '\x5', '@', '!', '\x2', '\x135', '\x133', 
		'\x3', '\x2', '\x2', '\x2', '\x136', '\x139', '\x3', '\x2', '\x2', '\x2', 
		'\x137', '\x135', '\x3', '\x2', '\x2', '\x2', '\x137', '\x138', '\x3', 
		'\x2', '\x2', '\x2', '\x138', '\x13B', '\x3', '\x2', '\x2', '\x2', '\x139', 
		'\x137', '\x3', '\x2', '\x2', '\x2', '\x13A', '\x132', '\x3', '\x2', '\x2', 
		'\x2', '\x13A', '\x13B', '\x3', '\x2', '\x2', '\x2', '\x13B', '\x13C', 
		'\x3', '\x2', '\x2', '\x2', '\x13C', '\x13D', '\a', '%', '\x2', '\x2', 
		'\x13D', '?', '\x3', '\x2', '\x2', '\x2', '\x13E', '\x141', '\x5', '\x1C', 
		'\xF', '\x2', '\x13F', '\x140', '\a', '&', '\x2', '\x2', '\x140', '\x142', 
		'\x5', '\x1C', '\xF', '\x2', '\x141', '\x13F', '\x3', '\x2', '\x2', '\x2', 
		'\x141', '\x142', '\x3', '\x2', '\x2', '\x2', '\x142', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x143', '\x146', '\x5', 'H', '%', '\x2', '\x144', 
		'\x145', '\a', '\x5', '\x2', '\x2', '\x145', '\x147', '\a', '\x31', '\x2', 
		'\x2', '\x146', '\x144', '\x3', '\x2', '\x2', '\x2', '\x146', '\x147', 
		'\x3', '\x2', '\x2', '\x2', '\x147', '\x149', '\x3', '\x2', '\x2', '\x2', 
		'\x148', '\x14A', '\x5', 'J', '&', '\x2', '\x149', '\x148', '\x3', '\x2', 
		'\x2', '\x2', '\x149', '\x14A', '\x3', '\x2', '\x2', '\x2', '\x14A', '\x14C', 
		'\x3', '\x2', '\x2', '\x2', '\x14B', '\x14D', '\x5', '\x44', '#', '\x2', 
		'\x14C', '\x14B', '\x3', '\x2', '\x2', '\x2', '\x14C', '\x14D', '\x3', 
		'\x2', '\x2', '\x2', '\x14D', '\x14F', '\x3', '\x2', '\x2', '\x2', '\x14E', 
		'\x150', '\x5', '\x34', '\x1B', '\x2', '\x14F', '\x14E', '\x3', '\x2', 
		'\x2', '\x2', '\x14F', '\x150', '\x3', '\x2', '\x2', '\x2', '\x150', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\x151', '\x152', '\a', '\'', '\x2', '\x2', 
		'\x152', '\x153', '\x5', 'L', '\'', '\x2', '\x153', '\x154', '\a', '(', 
		'\x2', '\x2', '\x154', '\x45', '\x3', '\x2', '\x2', '\x2', '\x155', '\x15A', 
		'\a', '\x30', '\x2', '\x2', '\x156', '\x157', '\a', '\x1A', '\x2', '\x2', 
		'\x157', '\x159', '\a', '\x30', '\x2', '\x2', '\x158', '\x156', '\x3', 
		'\x2', '\x2', '\x2', '\x159', '\x15C', '\x3', '\x2', '\x2', '\x2', '\x15A', 
		'\x158', '\x3', '\x2', '\x2', '\x2', '\x15A', '\x15B', '\x3', '\x2', '\x2', 
		'\x2', '\x15B', '\x15F', '\x3', '\x2', '\x2', '\x2', '\x15C', '\x15A', 
		'\x3', '\x2', '\x2', '\x2', '\x15D', '\x15E', '\a', '\x6', '\x2', '\x2', 
		'\x15E', '\x160', '\x5', '<', '\x1F', '\x2', '\x15F', '\x15D', '\x3', 
		'\x2', '\x2', '\x2', '\x15F', '\x160', '\x3', '\x2', '\x2', '\x2', '\x160', 
		'\x168', '\x3', '\x2', '\x2', '\x2', '\x161', '\x162', '\a', '\x1C', '\x2', 
		'\x2', '\x162', '\x163', '\a', '\x30', '\x2', '\x2', '\x163', '\x164', 
		'\a', '\x6', '\x2', '\x2', '\x164', '\x165', '\x5', '\x14', '\v', '\x2', 
		'\x165', '\x166', '\a', '\v', '\x2', '\x2', '\x166', '\x167', '\x5', '\x1C', 
		'\xF', '\x2', '\x167', '\x169', '\x3', '\x2', '\x2', '\x2', '\x168', '\x161', 
		'\x3', '\x2', '\x2', '\x2', '\x168', '\x169', '\x3', '\x2', '\x2', '\x2', 
		'\x169', '\x16A', '\x3', '\x2', '\x2', '\x2', '\x16A', '\x16B', '\a', 
		')', '\x2', '\x2', '\x16B', 'G', '\x3', '\x2', '\x2', '\x2', '\x16C', 
		'\x171', '\a', '\x30', '\x2', '\x2', '\x16D', '\x16E', '\a', '\b', '\x2', 
		'\x2', '\x16E', '\x170', '\a', '\x30', '\x2', '\x2', '\x16F', '\x16D', 
		'\x3', '\x2', '\x2', '\x2', '\x170', '\x173', '\x3', '\x2', '\x2', '\x2', 
		'\x171', '\x16F', '\x3', '\x2', '\x2', '\x2', '\x171', '\x172', '\x3', 
		'\x2', '\x2', '\x2', '\x172', 'I', '\x3', '\x2', '\x2', '\x2', '\x173', 
		'\x171', '\x3', '\x2', '\x2', '\x2', '\x174', '\x175', '\a', '\x5', '\x2', 
		'\x2', '\x175', '\x176', '\a', '*', '\x2', '\x2', '\x176', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\x177', '\x17C', '\x5', '\x1C', '\xF', '\x2', '\x178', 
		'\x179', '\a', '\x1A', '\x2', '\x2', '\x179', '\x17B', '\x5', '\x1C', 
		'\xF', '\x2', '\x17A', '\x178', '\x3', '\x2', '\x2', '\x2', '\x17B', '\x17E', 
		'\x3', '\x2', '\x2', '\x2', '\x17C', '\x17A', '\x3', '\x2', '\x2', '\x2', 
		'\x17C', '\x17D', '\x3', '\x2', '\x2', '\x2', '\x17D', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\x17E', '\x17C', '\x3', '\x2', '\x2', '\x2', '\x17F', '\x180', 
		'\t', '\x5', '\x2', '\x2', '\x180', 'O', '\x3', '\x2', '\x2', '\x2', '\x181', 
		'\x182', '\t', '\x6', '\x2', '\x2', '\x182', 'Q', '\x3', '\x2', '\x2', 
		'\x2', '\x183', '\x184', '\t', '\a', '\x2', '\x2', '\x184', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x185', '\x186', '\t', '\b', '\x2', '\x2', '\x186', 
		'U', '\x3', '\x2', '\x2', '\x2', '\x187', '\x188', '\t', '\t', '\x2', 
		'\x2', '\x188', 'W', '\x3', '\x2', '\x2', '\x2', '\x189', '\x18A', '\t', 
		'\n', '\x2', '\x2', '\x18A', 'Y', '\x3', '\x2', '\x2', '\x2', '(', '\x61', 
		'h', 'p', 'v', '{', '\x81', '\x8B', '\x98', '\x9B', '\x9F', '\xA9', '\xB8', 
		'\xBC', '\xCF', '\xD7', '\xDF', '\xE6', '\xEE', '\xF7', '\xFE', '\x105', 
		'\x110', '\x114', '\x117', '\x11E', '\x12B', '\x137', '\x13A', '\x141', 
		'\x146', '\x149', '\x14C', '\x14F', '\x15A', '\x15F', '\x168', '\x171', 
		'\x17C',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
