//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Hello.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class HelloParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, Stereotype=44, LOWERCASE=45, 
		UPPERCASE=46, DIGITS=47, NAME=48, NUMBER=49, WS=50;
	public const int
		RULE_oclFile = 0, RULE_packageName = 1, RULE_oclExpressions = 2, RULE_constraint = 3, 
		RULE_contextDeclaration = 4, RULE_classifierContext = 5, RULE_operationContext = 6, 
		RULE_operationName = 7, RULE_formalParameterList = 8, RULE_typeSpecifier = 9, 
		RULE_collectionType = 10, RULE_oclExpression = 11, RULE_returnType = 12, 
		RULE_expression = 13, RULE_letExpression = 14, RULE_ifExpression = 15, 
		RULE_logicalExpression = 16, RULE_relationalExpression = 17, RULE_additiveExpression = 18, 
		RULE_multiplicativeExpression = 19, RULE_unaryExpression = 20, RULE_postfixExpression = 21, 
		RULE_primaryExpression = 22, RULE_propertyCallParameters = 23, RULE_literal = 24, 
		RULE_enumLiteral = 25, RULE_simpleTypeSpecifier = 26, RULE_literalCollection = 27, 
		RULE_collectionItem = 28, RULE_propertyCall = 29, RULE_qualifiers = 30, 
		RULE_declarator = 31, RULE_pathName = 32, RULE_timeExpression = 33, RULE_actualParameterList = 34, 
		RULE_logicalOperator = 35, RULE_collectionKind = 36, RULE_relationalOperator = 37, 
		RULE_addOperator = 38, RULE_multiplyOperator = 39, RULE_unaryOperator = 40;
	public static readonly string[] ruleNames = {
		"oclFile", "packageName", "oclExpressions", "constraint", "contextDeclaration", 
		"classifierContext", "operationContext", "operationName", "formalParameterList", 
		"typeSpecifier", "collectionType", "oclExpression", "returnType", "expression", 
		"letExpression", "ifExpression", "logicalExpression", "relationalExpression", 
		"additiveExpression", "multiplicativeExpression", "unaryExpression", "postfixExpression", 
		"primaryExpression", "propertyCallParameters", "literal", "enumLiteral", 
		"simpleTypeSpecifier", "literalCollection", "collectionItem", "propertyCall", 
		"qualifiers", "declarator", "pathName", "timeExpression", "actualParameterList", 
		"logicalOperator", "collectionKind", "relationalOperator", "addOperator", 
		"multiplyOperator", "unaryOperator"
	};

	private static readonly string[] _LiteralNames = {
		null, "'package'", "'endpackage'", "'@'", "':'", "'context'", "'::'", 
		"'('", "')'", "'='", "'+'", "'-'", "'<'", "'<='", "'>='", "'>'", "'/'", 
		"'*'", "'<>'", "'implies'", "'not'", "'or'", "'xor'", "'and'", "','", 
		"'let'", "';'", "'if'", "'then'", "'else'", "'endif'", "'.'", "'->'", 
		"'{'", "'}'", "'..'", "'['", "']'", "'|'", "'pre'", "'Set'", "'Bag'", 
		"'Sequence'", "'Collection'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "Stereotype", "LOWERCASE", 
		"UPPERCASE", "DIGITS", "NAME", "NUMBER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Hello.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static HelloParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public HelloParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public HelloParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class OclFileContext : ParserRuleContext {
		public PackageNameContext[] packageName() {
			return GetRuleContexts<PackageNameContext>();
		}
		public PackageNameContext packageName(int i) {
			return GetRuleContext<PackageNameContext>(i);
		}
		public OclExpressionsContext[] oclExpressions() {
			return GetRuleContexts<OclExpressionsContext>();
		}
		public OclExpressionsContext oclExpressions(int i) {
			return GetRuleContext<OclExpressionsContext>(i);
		}
		public OclFileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oclFile; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOclFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OclFileContext oclFile() {
		OclFileContext _localctx = new OclFileContext(Context, State);
		EnterRule(_localctx, 0, RULE_oclFile);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 82; Match(T__0);
				State = 83; packageName();
				State = 84; oclExpressions();
				State = 85; Match(T__1);
				}
				}
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__0 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PackageNameContext : ParserRuleContext {
		public PathNameContext pathName() {
			return GetRuleContext<PathNameContext>(0);
		}
		public PackageNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_packageName; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPackageName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PackageNameContext packageName() {
		PackageNameContext _localctx = new PackageNameContext(Context, State);
		EnterRule(_localctx, 2, RULE_packageName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91; pathName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OclExpressionsContext : ParserRuleContext {
		public ConstraintContext[] constraint() {
			return GetRuleContexts<ConstraintContext>();
		}
		public ConstraintContext constraint(int i) {
			return GetRuleContext<ConstraintContext>(i);
		}
		public OclExpressionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oclExpressions; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOclExpressions(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OclExpressionsContext oclExpressions() {
		OclExpressionsContext _localctx = new OclExpressionsContext(Context, State);
		EnterRule(_localctx, 4, RULE_oclExpressions);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 93; constraint();
				}
				}
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstraintContext : ParserRuleContext {
		public ContextDeclarationContext contextDeclaration() {
			return GetRuleContext<ContextDeclarationContext>(0);
		}
		public ITerminalNode[] Stereotype() { return GetTokens(HelloParser.Stereotype); }
		public ITerminalNode Stereotype(int i) {
			return GetToken(HelloParser.Stereotype, i);
		}
		public ITerminalNode[] NUMBER() { return GetTokens(HelloParser.NUMBER); }
		public ITerminalNode NUMBER(int i) {
			return GetToken(HelloParser.NUMBER, i);
		}
		public OclExpressionContext[] oclExpression() {
			return GetRuleContexts<OclExpressionContext>();
		}
		public OclExpressionContext oclExpression(int i) {
			return GetRuleContext<OclExpressionContext>(i);
		}
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public ConstraintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constraint; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstraint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConstraintContext constraint() {
		ConstraintContext _localctx = new ConstraintContext(Context, State);
		EnterRule(_localctx, 6, RULE_constraint);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; contextDeclaration();
			State = 108;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 100; Match(Stereotype);
				State = 101; Match(T__2);
				State = 102; Match(NUMBER);
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NAME) {
					{
					State = 103; Match(NAME);
					}
				}

				State = 106; Match(T__3);
				State = 107; oclExpression();
				}
				}
				State = 110;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Stereotype );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContextDeclarationContext : ParserRuleContext {
		public OperationContextContext operationContext() {
			return GetRuleContext<OperationContextContext>(0);
		}
		public ClassifierContextContext classifierContext() {
			return GetRuleContext<ClassifierContextContext>(0);
		}
		public ContextDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_contextDeclaration; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContextDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContextDeclarationContext contextDeclaration() {
		ContextDeclarationContext _localctx = new ContextDeclarationContext(Context, State);
		EnterRule(_localctx, 8, RULE_contextDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112; Match(T__4);
			State = 115;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				State = 113; operationContext();
				}
				break;
			case 2:
				{
				State = 114; classifierContext();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassifierContextContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public ClassifierContextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classifierContext; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassifierContext(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassifierContextContext classifierContext() {
		ClassifierContextContext _localctx = new ClassifierContextContext(Context, State);
		EnterRule(_localctx, 10, RULE_classifierContext);
		try {
			State = 121;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 117; Match(NAME);
				State = 118; Match(T__3);
				State = 119; Match(NAME);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 120; Match(NAME);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContextContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public OperationNameContext operationName() {
			return GetRuleContext<OperationNameContext>(0);
		}
		public FormalParameterListContext formalParameterList() {
			return GetRuleContext<FormalParameterListContext>(0);
		}
		public ReturnTypeContext returnType() {
			return GetRuleContext<ReturnTypeContext>(0);
		}
		public OperationContextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operationContext; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperationContext(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationContextContext operationContext() {
		OperationContextContext _localctx = new OperationContextContext(Context, State);
		EnterRule(_localctx, 12, RULE_operationContext);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123; Match(NAME);
			State = 124; Match(T__5);
			State = 125; operationName();
			State = 126; Match(T__6);
			State = 127; formalParameterList();
			State = 128; Match(T__7);
			State = 131;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 129; Match(T__3);
				State = 130; returnType();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationNameContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public OperationNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operationName; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperationName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationNameContext operationName() {
		OperationNameContext _localctx = new OperationNameContext(Context, State);
		EnterRule(_localctx, 14, RULE_operationName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__9) | (1L << T__10) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << T__20) | (1L << T__21) | (1L << T__22) | (1L << NAME))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormalParameterListContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public TypeSpecifierContext[] typeSpecifier() {
			return GetRuleContexts<TypeSpecifierContext>();
		}
		public TypeSpecifierContext typeSpecifier(int i) {
			return GetRuleContext<TypeSpecifierContext>(i);
		}
		public FormalParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formalParameterList; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormalParameterList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalParameterListContext formalParameterList() {
		FormalParameterListContext _localctx = new FormalParameterListContext(Context, State);
		EnterRule(_localctx, 16, RULE_formalParameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NAME) {
				{
				State = 135; Match(NAME);
				State = 136; Match(T__3);
				State = 137; typeSpecifier();
				State = 144;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__23) {
					{
					{
					State = 138; Match(T__23);
					State = 139; Match(NAME);
					State = 140; Match(T__3);
					State = 141; typeSpecifier();
					}
					}
					State = 146;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeSpecifierContext : ParserRuleContext {
		public SimpleTypeSpecifierContext simpleTypeSpecifier() {
			return GetRuleContext<SimpleTypeSpecifierContext>(0);
		}
		public CollectionTypeContext collectionType() {
			return GetRuleContext<CollectionTypeContext>(0);
		}
		public TypeSpecifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeSpecifier; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeSpecifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeSpecifierContext typeSpecifier() {
		TypeSpecifierContext _localctx = new TypeSpecifierContext(Context, State);
		EnterRule(_localctx, 18, RULE_typeSpecifier);
		try {
			State = 151;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NAME:
				EnterOuterAlt(_localctx, 1);
				{
				State = 149; simpleTypeSpecifier();
				}
				break;
			case T__39:
			case T__40:
			case T__41:
			case T__42:
				EnterOuterAlt(_localctx, 2);
				{
				State = 150; collectionType();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionTypeContext : ParserRuleContext {
		public CollectionKindContext collectionKind() {
			return GetRuleContext<CollectionKindContext>(0);
		}
		public SimpleTypeSpecifierContext simpleTypeSpecifier() {
			return GetRuleContext<SimpleTypeSpecifierContext>(0);
		}
		public CollectionTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionType; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCollectionType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CollectionTypeContext collectionType() {
		CollectionTypeContext _localctx = new CollectionTypeContext(Context, State);
		EnterRule(_localctx, 20, RULE_collectionType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153; collectionKind();
			State = 154; Match(T__6);
			State = 155; simpleTypeSpecifier();
			State = 156; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OclExpressionContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LetExpressionContext[] letExpression() {
			return GetRuleContexts<LetExpressionContext>();
		}
		public LetExpressionContext letExpression(int i) {
			return GetRuleContext<LetExpressionContext>(i);
		}
		public OclExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_oclExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOclExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OclExpressionContext oclExpression() {
		OclExpressionContext _localctx = new OclExpressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_oclExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__24) {
				{
				{
				State = 158; letExpression();
				}
				}
				State = 163;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 164; expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnTypeContext : ParserRuleContext {
		public TypeSpecifierContext typeSpecifier() {
			return GetRuleContext<TypeSpecifierContext>(0);
		}
		public ReturnTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnType; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnTypeContext returnType() {
		ReturnTypeContext _localctx = new ReturnTypeContext(Context, State);
		EnterRule(_localctx, 24, RULE_returnType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166; typeSpecifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public LogicalExpressionContext logicalExpression() {
			return GetRuleContext<LogicalExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 26, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168; logicalExpression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LetExpressionContext : ParserRuleContext {
		public ITerminalNode NAME() { return GetToken(HelloParser.NAME, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public FormalParameterListContext formalParameterList() {
			return GetRuleContext<FormalParameterListContext>(0);
		}
		public TypeSpecifierContext typeSpecifier() {
			return GetRuleContext<TypeSpecifierContext>(0);
		}
		public LetExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetExpressionContext letExpression() {
		LetExpressionContext _localctx = new LetExpressionContext(Context, State);
		EnterRule(_localctx, 28, RULE_letExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170; Match(T__24);
			State = 171; Match(NAME);
			State = 176;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 172; Match(T__6);
				State = 173; formalParameterList();
				State = 174; Match(T__7);
				}
			}

			State = 180;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 178; Match(T__3);
				State = 179; typeSpecifier();
				}
			}

			State = 182; Match(T__8);
			State = 183; expression();
			State = 184; Match(T__25);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfExpressionContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public IfExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfExpressionContext ifExpression() {
		IfExpressionContext _localctx = new IfExpressionContext(Context, State);
		EnterRule(_localctx, 30, RULE_ifExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186; Match(T__26);
			State = 187; expression();
			State = 188; Match(T__27);
			State = 189; expression();
			State = 190; Match(T__28);
			State = 191; expression();
			State = 192; Match(T__29);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExpressionContext : ParserRuleContext {
		public RelationalExpressionContext[] relationalExpression() {
			return GetRuleContexts<RelationalExpressionContext>();
		}
		public RelationalExpressionContext relationalExpression(int i) {
			return GetRuleContext<RelationalExpressionContext>(i);
		}
		public LogicalOperatorContext[] logicalOperator() {
			return GetRuleContexts<LogicalOperatorContext>();
		}
		public LogicalOperatorContext logicalOperator(int i) {
			return GetRuleContext<LogicalOperatorContext>(i);
		}
		public LogicalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalExpressionContext logicalExpression() {
		LogicalExpressionContext _localctx = new LogicalExpressionContext(Context, State);
		EnterRule(_localctx, 32, RULE_logicalExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194; relationalExpression();
			State = 200;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__18) | (1L << T__20) | (1L << T__21) | (1L << T__22))) != 0)) {
				{
				{
				State = 195; logicalOperator();
				State = 196; relationalExpression();
				}
				}
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationalExpressionContext : ParserRuleContext {
		public AdditiveExpressionContext[] additiveExpression() {
			return GetRuleContexts<AdditiveExpressionContext>();
		}
		public AdditiveExpressionContext additiveExpression(int i) {
			return GetRuleContext<AdditiveExpressionContext>(i);
		}
		public RelationalOperatorContext relationalOperator() {
			return GetRuleContext<RelationalOperatorContext>(0);
		}
		public RelationalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationalExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalExpressionContext relationalExpression() {
		RelationalExpressionContext _localctx = new RelationalExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_relationalExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203; additiveExpression();
			State = 207;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__17))) != 0)) {
				{
				State = 204; relationalOperator();
				State = 205; additiveExpression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AdditiveExpressionContext : ParserRuleContext {
		public MultiplicativeExpressionContext[] multiplicativeExpression() {
			return GetRuleContexts<MultiplicativeExpressionContext>();
		}
		public MultiplicativeExpressionContext multiplicativeExpression(int i) {
			return GetRuleContext<MultiplicativeExpressionContext>(i);
		}
		public AddOperatorContext[] addOperator() {
			return GetRuleContexts<AddOperatorContext>();
		}
		public AddOperatorContext addOperator(int i) {
			return GetRuleContext<AddOperatorContext>(i);
		}
		public AdditiveExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additiveExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditiveExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AdditiveExpressionContext additiveExpression() {
		AdditiveExpressionContext _localctx = new AdditiveExpressionContext(Context, State);
		EnterRule(_localctx, 36, RULE_additiveExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209; multiplicativeExpression();
			State = 215;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__9 || _la==T__10) {
				{
				{
				State = 210; addOperator();
				State = 211; multiplicativeExpression();
				}
				}
				State = 217;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiplicativeExpressionContext : ParserRuleContext {
		public UnaryExpressionContext[] unaryExpression() {
			return GetRuleContexts<UnaryExpressionContext>();
		}
		public UnaryExpressionContext unaryExpression(int i) {
			return GetRuleContext<UnaryExpressionContext>(i);
		}
		public MultiplyOperatorContext[] multiplyOperator() {
			return GetRuleContexts<MultiplyOperatorContext>();
		}
		public MultiplyOperatorContext multiplyOperator(int i) {
			return GetRuleContext<MultiplyOperatorContext>(i);
		}
		public MultiplicativeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplicativeExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicativeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplicativeExpressionContext multiplicativeExpression() {
		MultiplicativeExpressionContext _localctx = new MultiplicativeExpressionContext(Context, State);
		EnterRule(_localctx, 38, RULE_multiplicativeExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 218; unaryExpression();
			State = 224;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__15 || _la==T__16) {
				{
				{
				State = 219; multiplyOperator();
				State = 220; unaryExpression();
				}
				}
				State = 226;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		public UnaryOperatorContext unaryOperator() {
			return GetRuleContext<UnaryOperatorContext>(0);
		}
		public PostfixExpressionContext postfixExpression() {
			return GetRuleContext<PostfixExpressionContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 40, RULE_unaryExpression);
		try {
			State = 231;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__10:
			case T__19:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 227; unaryOperator();
				State = 228; postfixExpression();
				}
				}
				break;
			case T__6:
			case T__26:
			case T__39:
			case T__40:
			case T__41:
			case T__42:
			case NAME:
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 230; postfixExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PostfixExpressionContext : ParserRuleContext {
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public PropertyCallContext[] propertyCall() {
			return GetRuleContexts<PropertyCallContext>();
		}
		public PropertyCallContext propertyCall(int i) {
			return GetRuleContext<PropertyCallContext>(i);
		}
		public PostfixExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postfixExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPostfixExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PostfixExpressionContext postfixExpression() {
		PostfixExpressionContext _localctx = new PostfixExpressionContext(Context, State);
		EnterRule(_localctx, 42, RULE_postfixExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233; primaryExpression();
			State = 238;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__30 || _la==T__31) {
				{
				{
				State = 234;
				_la = TokenStream.LA(1);
				if ( !(_la==T__30 || _la==T__31) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 235; propertyCall();
				}
				}
				State = 240;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryExpressionContext : ParserRuleContext {
		public LiteralCollectionContext literalCollection() {
			return GetRuleContext<LiteralCollectionContext>(0);
		}
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public PropertyCallContext propertyCall() {
			return GetRuleContext<PropertyCallContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public IfExpressionContext ifExpression() {
			return GetRuleContext<IfExpressionContext>(0);
		}
		public PrimaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primaryExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryExpressionContext primaryExpression() {
		PrimaryExpressionContext _localctx = new PrimaryExpressionContext(Context, State);
		EnterRule(_localctx, 44, RULE_primaryExpression);
		try {
			State = 249;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 241; literalCollection();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 242; literal();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 243; propertyCall();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 244; Match(T__6);
				State = 245; expression();
				State = 246; Match(T__7);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 248; ifExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyCallParametersContext : ParserRuleContext {
		public DeclaratorContext declarator() {
			return GetRuleContext<DeclaratorContext>(0);
		}
		public ActualParameterListContext actualParameterList() {
			return GetRuleContext<ActualParameterListContext>(0);
		}
		public PropertyCallParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyCallParameters; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyCallParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyCallParametersContext propertyCallParameters() {
		PropertyCallParametersContext _localctx = new PropertyCallParametersContext(Context, State);
		EnterRule(_localctx, 46, RULE_propertyCallParameters);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 251; Match(T__6);
			State = 253;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
			case 1:
				{
				State = 252; declarator();
				}
				break;
			}
			State = 256;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__6) | (1L << T__10) | (1L << T__19) | (1L << T__26) | (1L << T__39) | (1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << NAME) | (1L << NUMBER))) != 0)) {
				{
				State = 255; actualParameterList();
				}
			}

			State = 258; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode NUMBER() { return GetToken(HelloParser.NUMBER, 0); }
		public EnumLiteralContext enumLiteral() {
			return GetRuleContext<EnumLiteralContext>(0);
		}
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 48, RULE_literal);
		try {
			State = 262;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 260; Match(NUMBER);
				}
				break;
			case NAME:
				EnterOuterAlt(_localctx, 2);
				{
				State = 261; enumLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumLiteralContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public EnumLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumLiteral; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumLiteralContext enumLiteral() {
		EnumLiteralContext _localctx = new EnumLiteralContext(Context, State);
		EnterRule(_localctx, 50, RULE_enumLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 264; Match(NAME);
			State = 265; Match(T__5);
			State = 266; Match(NAME);
			State = 271;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 267; Match(T__5);
				State = 268; Match(NAME);
				}
				}
				State = 273;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleTypeSpecifierContext : ParserRuleContext {
		public PathNameContext pathName() {
			return GetRuleContext<PathNameContext>(0);
		}
		public SimpleTypeSpecifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleTypeSpecifier; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimpleTypeSpecifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SimpleTypeSpecifierContext simpleTypeSpecifier() {
		SimpleTypeSpecifierContext _localctx = new SimpleTypeSpecifierContext(Context, State);
		EnterRule(_localctx, 52, RULE_simpleTypeSpecifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 274; pathName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralCollectionContext : ParserRuleContext {
		public CollectionKindContext collectionKind() {
			return GetRuleContext<CollectionKindContext>(0);
		}
		public CollectionItemContext[] collectionItem() {
			return GetRuleContexts<CollectionItemContext>();
		}
		public CollectionItemContext collectionItem(int i) {
			return GetRuleContext<CollectionItemContext>(i);
		}
		public LiteralCollectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literalCollection; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteralCollection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralCollectionContext literalCollection() {
		LiteralCollectionContext _localctx = new LiteralCollectionContext(Context, State);
		EnterRule(_localctx, 54, RULE_literalCollection);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 276; collectionKind();
			State = 277; Match(T__32);
			State = 286;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__6) | (1L << T__10) | (1L << T__19) | (1L << T__26) | (1L << T__39) | (1L << T__40) | (1L << T__41) | (1L << T__42) | (1L << NAME) | (1L << NUMBER))) != 0)) {
				{
				State = 278; collectionItem();
				State = 283;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__23) {
					{
					{
					State = 279; Match(T__23);
					State = 280; collectionItem();
					}
					}
					State = 285;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 288; Match(T__33);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionItemContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public CollectionItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionItem; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCollectionItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CollectionItemContext collectionItem() {
		CollectionItemContext _localctx = new CollectionItemContext(Context, State);
		EnterRule(_localctx, 56, RULE_collectionItem);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 290; expression();
			State = 293;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__34) {
				{
				State = 291; Match(T__34);
				State = 292; expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyCallContext : ParserRuleContext {
		public PathNameContext pathName() {
			return GetRuleContext<PathNameContext>(0);
		}
		public ITerminalNode NUMBER() { return GetToken(HelloParser.NUMBER, 0); }
		public TimeExpressionContext timeExpression() {
			return GetRuleContext<TimeExpressionContext>(0);
		}
		public QualifiersContext qualifiers() {
			return GetRuleContext<QualifiersContext>(0);
		}
		public PropertyCallParametersContext propertyCallParameters() {
			return GetRuleContext<PropertyCallParametersContext>(0);
		}
		public PropertyCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyCall; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyCallContext propertyCall() {
		PropertyCallContext _localctx = new PropertyCallContext(Context, State);
		EnterRule(_localctx, 58, RULE_propertyCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 295; pathName();
			State = 298;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
			case 1:
				{
				State = 296; Match(T__2);
				State = 297; Match(NUMBER);
				}
				break;
			}
			State = 301;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 300; timeExpression();
				}
			}

			State = 304;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__35) {
				{
				State = 303; qualifiers();
				}
			}

			State = 307;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 306; propertyCallParameters();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiersContext : ParserRuleContext {
		public ActualParameterListContext actualParameterList() {
			return GetRuleContext<ActualParameterListContext>(0);
		}
		public QualifiersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiers; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualifiers(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QualifiersContext qualifiers() {
		QualifiersContext _localctx = new QualifiersContext(Context, State);
		EnterRule(_localctx, 60, RULE_qualifiers);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 309; Match(T__35);
			State = 310; actualParameterList();
			State = 311; Match(T__36);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclaratorContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public SimpleTypeSpecifierContext simpleTypeSpecifier() {
			return GetRuleContext<SimpleTypeSpecifierContext>(0);
		}
		public TypeSpecifierContext typeSpecifier() {
			return GetRuleContext<TypeSpecifierContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public DeclaratorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declarator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclarator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclaratorContext declarator() {
		DeclaratorContext _localctx = new DeclaratorContext(Context, State);
		EnterRule(_localctx, 62, RULE_declarator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 313; Match(NAME);
			State = 318;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__23) {
				{
				{
				State = 314; Match(T__23);
				State = 315; Match(NAME);
				}
				}
				State = 320;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 323;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 321; Match(T__3);
				State = 322; simpleTypeSpecifier();
				}
			}

			State = 332;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__25) {
				{
				State = 325; Match(T__25);
				State = 326; Match(NAME);
				State = 327; Match(T__3);
				State = 328; typeSpecifier();
				State = 329; Match(T__8);
				State = 330; expression();
				}
			}

			State = 334; Match(T__37);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PathNameContext : ParserRuleContext {
		public ITerminalNode[] NAME() { return GetTokens(HelloParser.NAME); }
		public ITerminalNode NAME(int i) {
			return GetToken(HelloParser.NAME, i);
		}
		public PathNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pathName; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPathName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PathNameContext pathName() {
		PathNameContext _localctx = new PathNameContext(Context, State);
		EnterRule(_localctx, 64, RULE_pathName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 336; Match(NAME);
			State = 341;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 337; Match(T__5);
				State = 338; Match(NAME);
				}
				}
				State = 343;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeExpressionContext : ParserRuleContext {
		public TimeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeExpressionContext timeExpression() {
		TimeExpressionContext _localctx = new TimeExpressionContext(Context, State);
		EnterRule(_localctx, 66, RULE_timeExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 344; Match(T__2);
			State = 345; Match(T__38);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActualParameterListContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ActualParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actualParameterList; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActualParameterList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActualParameterListContext actualParameterList() {
		ActualParameterListContext _localctx = new ActualParameterListContext(Context, State);
		EnterRule(_localctx, 68, RULE_actualParameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 347; expression();
			State = 352;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__23) {
				{
				{
				State = 348; Match(T__23);
				State = 349; expression();
				}
				}
				State = 354;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOperatorContext : ParserRuleContext {
		public LogicalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalOperatorContext logicalOperator() {
		LogicalOperatorContext _localctx = new LogicalOperatorContext(Context, State);
		EnterRule(_localctx, 70, RULE_logicalOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 355;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__18) | (1L << T__20) | (1L << T__21) | (1L << T__22))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CollectionKindContext : ParserRuleContext {
		public CollectionKindContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_collectionKind; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCollectionKind(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CollectionKindContext collectionKind() {
		CollectionKindContext _localctx = new CollectionKindContext(Context, State);
		EnterRule(_localctx, 72, RULE_collectionKind);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 357;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__39) | (1L << T__40) | (1L << T__41) | (1L << T__42))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationalOperatorContext : ParserRuleContext {
		public RelationalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationalOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalOperatorContext relationalOperator() {
		RelationalOperatorContext _localctx = new RelationalOperatorContext(Context, State);
		EnterRule(_localctx, 74, RULE_relationalOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 359;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << T__11) | (1L << T__12) | (1L << T__13) | (1L << T__14) | (1L << T__17))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddOperatorContext : ParserRuleContext {
		public AddOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AddOperatorContext addOperator() {
		AddOperatorContext _localctx = new AddOperatorContext(Context, State);
		EnterRule(_localctx, 76, RULE_addOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 361;
			_la = TokenStream.LA(1);
			if ( !(_la==T__9 || _la==T__10) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiplyOperatorContext : ParserRuleContext {
		public MultiplyOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplyOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplyOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplyOperatorContext multiplyOperator() {
		MultiplyOperatorContext _localctx = new MultiplyOperatorContext(Context, State);
		EnterRule(_localctx, 78, RULE_multiplyOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 363;
			_la = TokenStream.LA(1);
			if ( !(_la==T__15 || _la==T__16) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryOperatorContext : ParserRuleContext {
		public UnaryOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryOperator; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHelloVisitor<TResult> typedVisitor = visitor as IHelloVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryOperatorContext unaryOperator() {
		UnaryOperatorContext _localctx = new UnaryOperatorContext(Context, State);
		EnterRule(_localctx, 80, RULE_unaryOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 365;
			_la = TokenStream.LA(1);
			if ( !(_la==T__10 || _la==T__19) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x34', '\x172', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x6', '\x2', 'Z', '\n', '\x2', '\r', '\x2', 
		'\xE', '\x2', '[', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\a', '\x4', 
		'\x61', '\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x64', '\v', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', 
		'\x5', 'k', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x6', '\x5', 'o', 
		'\n', '\x5', '\r', '\x5', '\xE', '\x5', 'p', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x5', '\x6', 'v', '\n', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', '|', '\n', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x5', '\b', '\x86', '\n', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', '\x91', '\n', '\n', '\f', '\n', '\xE', 
		'\n', '\x94', '\v', '\n', '\x5', '\n', '\x96', '\n', '\n', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '\x9A', '\n', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\a', '\r', '\xA2', 
		'\n', '\r', '\f', '\r', '\xE', '\r', '\xA5', '\v', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x5', '\x10', '\xB3', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x5', '\x10', '\xB7', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', '\xC9', 
		'\n', '\x12', '\f', '\x12', '\xE', '\x12', '\xCC', '\v', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\xD2', 
		'\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\a', '\x14', '\xD8', '\n', '\x14', '\f', '\x14', '\xE', '\x14', '\xDB', 
		'\v', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\a', '\x15', '\xE1', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xE4', 
		'\v', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x5', '\x16', '\xEA', '\n', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\a', '\x17', '\xEF', '\n', '\x17', '\f', '\x17', '\xE', '\x17', 
		'\xF2', '\v', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x5', 
		'\x18', '\xFC', '\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x5', '\x19', 
		'\x100', '\n', '\x19', '\x3', '\x19', '\x5', '\x19', '\x103', '\n', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', 
		'\x109', '\n', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\a', '\x1B', '\x110', '\n', '\x1B', '\f', '\x1B', 
		'\xE', '\x1B', '\x113', '\v', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\a', 
		'\x1D', '\x11C', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', '\x11F', '\v', 
		'\x1D', '\x5', '\x1D', '\x121', '\n', '\x1D', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x5', '\x1E', '\x128', '\n', 
		'\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x5', '\x1F', '\x12D', 
		'\n', '\x1F', '\x3', '\x1F', '\x5', '\x1F', '\x130', '\n', '\x1F', '\x3', 
		'\x1F', '\x5', '\x1F', '\x133', '\n', '\x1F', '\x3', '\x1F', '\x5', '\x1F', 
		'\x136', '\n', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', 
		'\x3', '!', '\x3', '!', '\x3', '!', '\a', '!', '\x13F', '\n', '!', '\f', 
		'!', '\xE', '!', '\x142', '\v', '!', '\x3', '!', '\x3', '!', '\x5', '!', 
		'\x146', '\n', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', 
		'!', '\x3', '!', '\x3', '!', '\x5', '!', '\x14F', '\n', '!', '\x3', '!', 
		'\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\a', '\"', '\x156', 
		'\n', '\"', '\f', '\"', '\xE', '\"', '\x159', '\v', '\"', '\x3', '#', 
		'\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', '$', '\a', '$', 
		'\x161', '\n', '$', '\f', '$', '\xE', '$', '\x164', '\v', '$', '\x3', 
		'%', '\x3', '%', '\x3', '&', '\x3', '&', '\x3', '\'', '\x3', '\'', '\x3', 
		'(', '\x3', '(', '\x3', ')', '\x3', ')', '\x3', '*', '\x3', '*', '\x3', 
		'*', '\x2', '\x2', '+', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', 
		'\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', 
		'$', '&', '(', '*', ',', '.', '\x30', '\x32', '\x34', '\x36', '\x38', 
		':', '<', '>', '@', '\x42', '\x44', '\x46', 'H', 'J', 'L', 'N', 'P', 'R', 
		'\x2', '\n', '\x4', '\x2', '\v', '\x19', '\x32', '\x32', '\x3', '\x2', 
		'!', '\"', '\x4', '\x2', '\x15', '\x15', '\x17', '\x19', '\x3', '\x2', 
		'*', '-', '\x5', '\x2', '\v', '\v', '\xE', '\x11', '\x14', '\x14', '\x3', 
		'\x2', '\f', '\r', '\x3', '\x2', '\x12', '\x13', '\x4', '\x2', '\r', '\r', 
		'\x16', '\x16', '\x2', '\x16F', '\x2', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'\x4', ']', '\x3', '\x2', '\x2', '\x2', '\x6', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\b', '\x65', '\x3', '\x2', '\x2', '\x2', '\n', 'r', '\x3', '\x2', 
		'\x2', '\x2', '\f', '{', '\x3', '\x2', '\x2', '\x2', '\xE', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x10', '\x87', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x14', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x18', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\xA8', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', ' ', '\xBC', '\x3', '\x2', '\x2', '\x2', '\"', '\xC4', '\x3', '\x2', 
		'\x2', '\x2', '$', '\xCD', '\x3', '\x2', '\x2', '\x2', '&', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '(', '\xDC', '\x3', '\x2', '\x2', '\x2', '*', '\xE9', 
		'\x3', '\x2', '\x2', '\x2', ',', '\xEB', '\x3', '\x2', '\x2', '\x2', '.', 
		'\xFB', '\x3', '\x2', '\x2', '\x2', '\x30', '\xFD', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x108', '\x3', '\x2', '\x2', '\x2', '\x34', '\x10A', '\x3', 
		'\x2', '\x2', '\x2', '\x36', '\x114', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\x116', '\x3', '\x2', '\x2', '\x2', ':', '\x124', '\x3', '\x2', '\x2', 
		'\x2', '<', '\x129', '\x3', '\x2', '\x2', '\x2', '>', '\x137', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x13B', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x152', '\x3', '\x2', '\x2', '\x2', '\x44', '\x15A', '\x3', '\x2', '\x2', 
		'\x2', '\x46', '\x15D', '\x3', '\x2', '\x2', '\x2', 'H', '\x165', '\x3', 
		'\x2', '\x2', '\x2', 'J', '\x167', '\x3', '\x2', '\x2', '\x2', 'L', '\x169', 
		'\x3', '\x2', '\x2', '\x2', 'N', '\x16B', '\x3', '\x2', '\x2', '\x2', 
		'P', '\x16D', '\x3', '\x2', '\x2', '\x2', 'R', '\x16F', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'U', '\a', '\x3', '\x2', '\x2', 'U', 'V', '\x5', '\x4', 
		'\x3', '\x2', 'V', 'W', '\x5', '\x6', '\x4', '\x2', 'W', 'X', '\a', '\x4', 
		'\x2', '\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 'Y', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', 
		'\x2', '\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '\x3', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\x5', '\x42', '\"', '\x2', '^', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '_', '\x61', '\x5', '\b', '\x5', '\x2', '`', 
		'_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\a', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x65', 'n', '\x5', '\n', '\x6', '\x2', 
		'\x66', 'g', '\a', '.', '\x2', '\x2', 'g', 'h', '\a', '\x5', '\x2', '\x2', 
		'h', 'j', '\a', '\x33', '\x2', '\x2', 'i', 'k', '\a', '\x32', '\x2', '\x2', 
		'j', 'i', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '\x6', '\x2', '\x2', 
		'm', 'o', '\x5', '\x18', '\r', '\x2', 'n', '\x66', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', '\t', '\x3', '\x2', 
		'\x2', '\x2', 'r', 'u', '\a', '\a', '\x2', '\x2', 's', 'v', '\x5', '\xE', 
		'\b', '\x2', 't', 'v', '\x5', '\f', '\a', '\x2', 'u', 's', '\x3', '\x2', 
		'\x2', '\x2', 'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', '\v', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'x', '\a', '\x32', '\x2', '\x2', 'x', 'y', '\a', 
		'\x6', '\x2', '\x2', 'y', '|', '\a', '\x32', '\x2', '\x2', 'z', '|', '\a', 
		'\x32', '\x2', '\x2', '{', 'w', '\x3', '\x2', '\x2', '\x2', '{', 'z', 
		'\x3', '\x2', '\x2', '\x2', '|', '\r', '\x3', '\x2', '\x2', '\x2', '}', 
		'~', '\a', '\x32', '\x2', '\x2', '~', '\x7F', '\a', '\b', '\x2', '\x2', 
		'\x7F', '\x80', '\x5', '\x10', '\t', '\x2', '\x80', '\x81', '\a', '\t', 
		'\x2', '\x2', '\x81', '\x82', '\x5', '\x12', '\n', '\x2', '\x82', '\x85', 
		'\a', '\n', '\x2', '\x2', '\x83', '\x84', '\a', '\x6', '\x2', '\x2', '\x84', 
		'\x86', '\x5', '\x1A', '\xE', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x88', '\t', '\x2', '\x2', '\x2', '\x88', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', '\x32', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', '\x6', '\x2', '\x2', '\x8B', '\x92', '\x5', 
		'\x14', '\v', '\x2', '\x8C', '\x8D', '\a', '\x1A', '\x2', '\x2', '\x8D', 
		'\x8E', '\a', '\x32', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x6', '\x2', 
		'\x2', '\x8F', '\x91', '\x5', '\x14', '\v', '\x2', '\x90', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x94', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x96', '\x3', '\x2', '\x2', '\x2', '\x94', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x89', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\x9A', '\x5', '\x36', '\x1C', '\x2', '\x98', '\x9A', '\x5', 
		'\x16', '\f', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\x5', 'J', '&', '\x2', '\x9C', '\x9D', '\a', '\t', 
		'\x2', '\x2', '\x9D', '\x9E', '\x5', '\x36', '\x1C', '\x2', '\x9E', '\x9F', 
		'\a', '\n', '\x2', '\x2', '\x9F', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'\xA0', '\xA2', '\x5', '\x1E', '\x10', '\x2', '\xA1', '\xA0', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA3', '\x3', '\x2', 
		'\x2', '\x2', '\xA6', '\xA7', '\x5', '\x1C', '\xF', '\x2', '\xA7', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x5', '\x14', '\v', '\x2', 
		'\xA9', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x5', '\"', 
		'\x12', '\x2', '\xAB', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', 
		'\a', '\x1B', '\x2', '\x2', '\xAD', '\xB2', '\a', '\x32', '\x2', '\x2', 
		'\xAE', '\xAF', '\a', '\t', '\x2', '\x2', '\xAF', '\xB0', '\x5', '\x12', 
		'\n', '\x2', '\xB0', '\xB1', '\a', '\n', '\x2', '\x2', '\xB1', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xB2', '\xAE', '\x3', '\x2', '\x2', '\x2', 
		'\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB6', '\x3', '\x2', 
		'\x2', '\x2', '\xB4', '\xB5', '\a', '\x6', '\x2', '\x2', '\xB5', '\xB7', 
		'\x5', '\x14', '\v', '\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\x3', '\x2', 
		'\x2', '\x2', '\xB8', '\xB9', '\a', '\v', '\x2', '\x2', '\xB9', '\xBA', 
		'\x5', '\x1C', '\xF', '\x2', '\xBA', '\xBB', '\a', '\x1C', '\x2', '\x2', 
		'\xBB', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\a', '\x1D', 
		'\x2', '\x2', '\xBD', '\xBE', '\x5', '\x1C', '\xF', '\x2', '\xBE', '\xBF', 
		'\a', '\x1E', '\x2', '\x2', '\xBF', '\xC0', '\x5', '\x1C', '\xF', '\x2', 
		'\xC0', '\xC1', '\a', '\x1F', '\x2', '\x2', '\xC1', '\xC2', '\x5', '\x1C', 
		'\xF', '\x2', '\xC2', '\xC3', '\a', ' ', '\x2', '\x2', '\xC3', '!', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xCA', '\x5', '$', '\x13', '\x2', '\xC5', 
		'\xC6', '\x5', 'H', '%', '\x2', '\xC6', '\xC7', '\x5', '$', '\x13', '\x2', 
		'\xC7', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC5', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', '\x2', '\x2', '\x2', 
		'\xCB', '#', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', '\xCD', '\xD1', '\x5', '&', '\x14', '\x2', '\xCE', '\xCF', 
		'\x5', 'L', '\'', '\x2', '\xCF', '\xD0', '\x5', '&', '\x14', '\x2', '\xD0', 
		'\xD2', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD9', '\x5', '(', '\x15', '\x2', '\xD4', 
		'\xD5', '\x5', 'N', '(', '\x2', '\xD5', '\xD6', '\x5', '(', '\x15', '\x2', 
		'\xD6', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD4', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xD7', 
		'\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\x3', '\x2', '\x2', '\x2', 
		'\xDA', '\'', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\xDC', '\xE2', '\x5', '*', '\x16', '\x2', '\xDD', '\xDE', 
		'\x5', 'P', ')', '\x2', '\xDE', '\xDF', '\x5', '*', '\x16', '\x2', '\xDF', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xE1', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE0', '\x3', 
		'\x2', '\x2', '\x2', '\xE2', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', 
		')', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\xE6', '\x5', 'R', '*', '\x2', '\xE6', '\xE7', '\x5', 
		',', '\x17', '\x2', '\xE7', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xEA', '\x5', ',', '\x17', '\x2', '\xE9', '\xE5', '\x3', '\x2', '\x2', 
		'\x2', '\xE9', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xEA', '+', '\x3', 
		'\x2', '\x2', '\x2', '\xEB', '\xF0', '\x5', '.', '\x18', '\x2', '\xEC', 
		'\xED', '\t', '\x3', '\x2', '\x2', '\xED', '\xEF', '\x5', '<', '\x1F', 
		'\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\xF0', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xF1', '\x3', '\x2', '\x2', '\x2', '\xF1', '-', '\x3', '\x2', '\x2', 
		'\x2', '\xF2', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xFC', '\x5', 
		'\x38', '\x1D', '\x2', '\xF4', '\xFC', '\x5', '\x32', '\x1A', '\x2', '\xF5', 
		'\xFC', '\x5', '<', '\x1F', '\x2', '\xF6', '\xF7', '\a', '\t', '\x2', 
		'\x2', '\xF7', '\xF8', '\x5', '\x1C', '\xF', '\x2', '\xF8', '\xF9', '\a', 
		'\n', '\x2', '\x2', '\xF9', '\xFC', '\x3', '\x2', '\x2', '\x2', '\xFA', 
		'\xFC', '\x5', ' ', '\x11', '\x2', '\xFB', '\xF3', '\x3', '\x2', '\x2', 
		'\x2', '\xFB', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xF5', '\x3', 
		'\x2', '\x2', '\x2', '\xFB', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xFB', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', '\xFC', '/', '\x3', '\x2', '\x2', 
		'\x2', '\xFD', '\xFF', '\a', '\t', '\x2', '\x2', '\xFE', '\x100', '\x5', 
		'@', '!', '\x2', '\xFF', '\xFE', '\x3', '\x2', '\x2', '\x2', '\xFF', '\x100', 
		'\x3', '\x2', '\x2', '\x2', '\x100', '\x102', '\x3', '\x2', '\x2', '\x2', 
		'\x101', '\x103', '\x5', '\x46', '$', '\x2', '\x102', '\x101', '\x3', 
		'\x2', '\x2', '\x2', '\x102', '\x103', '\x3', '\x2', '\x2', '\x2', '\x103', 
		'\x104', '\x3', '\x2', '\x2', '\x2', '\x104', '\x105', '\a', '\n', '\x2', 
		'\x2', '\x105', '\x31', '\x3', '\x2', '\x2', '\x2', '\x106', '\x109', 
		'\a', '\x33', '\x2', '\x2', '\x107', '\x109', '\x5', '\x34', '\x1B', '\x2', 
		'\x108', '\x106', '\x3', '\x2', '\x2', '\x2', '\x108', '\x107', '\x3', 
		'\x2', '\x2', '\x2', '\x109', '\x33', '\x3', '\x2', '\x2', '\x2', '\x10A', 
		'\x10B', '\a', '\x32', '\x2', '\x2', '\x10B', '\x10C', '\a', '\b', '\x2', 
		'\x2', '\x10C', '\x111', '\a', '\x32', '\x2', '\x2', '\x10D', '\x10E', 
		'\a', '\b', '\x2', '\x2', '\x10E', '\x110', '\a', '\x32', '\x2', '\x2', 
		'\x10F', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x110', '\x113', '\x3', 
		'\x2', '\x2', '\x2', '\x111', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x111', 
		'\x112', '\x3', '\x2', '\x2', '\x2', '\x112', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x113', '\x111', '\x3', '\x2', '\x2', '\x2', '\x114', '\x115', 
		'\x5', '\x42', '\"', '\x2', '\x115', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x116', '\x117', '\x5', 'J', '&', '\x2', '\x117', '\x120', '\a', '#', 
		'\x2', '\x2', '\x118', '\x11D', '\x5', ':', '\x1E', '\x2', '\x119', '\x11A', 
		'\a', '\x1A', '\x2', '\x2', '\x11A', '\x11C', '\x5', ':', '\x1E', '\x2', 
		'\x11B', '\x119', '\x3', '\x2', '\x2', '\x2', '\x11C', '\x11F', '\x3', 
		'\x2', '\x2', '\x2', '\x11D', '\x11B', '\x3', '\x2', '\x2', '\x2', '\x11D', 
		'\x11E', '\x3', '\x2', '\x2', '\x2', '\x11E', '\x121', '\x3', '\x2', '\x2', 
		'\x2', '\x11F', '\x11D', '\x3', '\x2', '\x2', '\x2', '\x120', '\x118', 
		'\x3', '\x2', '\x2', '\x2', '\x120', '\x121', '\x3', '\x2', '\x2', '\x2', 
		'\x121', '\x122', '\x3', '\x2', '\x2', '\x2', '\x122', '\x123', '\a', 
		'$', '\x2', '\x2', '\x123', '\x39', '\x3', '\x2', '\x2', '\x2', '\x124', 
		'\x127', '\x5', '\x1C', '\xF', '\x2', '\x125', '\x126', '\a', '%', '\x2', 
		'\x2', '\x126', '\x128', '\x5', '\x1C', '\xF', '\x2', '\x127', '\x125', 
		'\x3', '\x2', '\x2', '\x2', '\x127', '\x128', '\x3', '\x2', '\x2', '\x2', 
		'\x128', ';', '\x3', '\x2', '\x2', '\x2', '\x129', '\x12C', '\x5', '\x42', 
		'\"', '\x2', '\x12A', '\x12B', '\a', '\x5', '\x2', '\x2', '\x12B', '\x12D', 
		'\a', '\x33', '\x2', '\x2', '\x12C', '\x12A', '\x3', '\x2', '\x2', '\x2', 
		'\x12C', '\x12D', '\x3', '\x2', '\x2', '\x2', '\x12D', '\x12F', '\x3', 
		'\x2', '\x2', '\x2', '\x12E', '\x130', '\x5', '\x44', '#', '\x2', '\x12F', 
		'\x12E', '\x3', '\x2', '\x2', '\x2', '\x12F', '\x130', '\x3', '\x2', '\x2', 
		'\x2', '\x130', '\x132', '\x3', '\x2', '\x2', '\x2', '\x131', '\x133', 
		'\x5', '>', ' ', '\x2', '\x132', '\x131', '\x3', '\x2', '\x2', '\x2', 
		'\x132', '\x133', '\x3', '\x2', '\x2', '\x2', '\x133', '\x135', '\x3', 
		'\x2', '\x2', '\x2', '\x134', '\x136', '\x5', '\x30', '\x19', '\x2', '\x135', 
		'\x134', '\x3', '\x2', '\x2', '\x2', '\x135', '\x136', '\x3', '\x2', '\x2', 
		'\x2', '\x136', '=', '\x3', '\x2', '\x2', '\x2', '\x137', '\x138', '\a', 
		'&', '\x2', '\x2', '\x138', '\x139', '\x5', '\x46', '$', '\x2', '\x139', 
		'\x13A', '\a', '\'', '\x2', '\x2', '\x13A', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x13B', '\x140', '\a', '\x32', '\x2', '\x2', '\x13C', '\x13D', 
		'\a', '\x1A', '\x2', '\x2', '\x13D', '\x13F', '\a', '\x32', '\x2', '\x2', 
		'\x13E', '\x13C', '\x3', '\x2', '\x2', '\x2', '\x13F', '\x142', '\x3', 
		'\x2', '\x2', '\x2', '\x140', '\x13E', '\x3', '\x2', '\x2', '\x2', '\x140', 
		'\x141', '\x3', '\x2', '\x2', '\x2', '\x141', '\x145', '\x3', '\x2', '\x2', 
		'\x2', '\x142', '\x140', '\x3', '\x2', '\x2', '\x2', '\x143', '\x144', 
		'\a', '\x6', '\x2', '\x2', '\x144', '\x146', '\x5', '\x36', '\x1C', '\x2', 
		'\x145', '\x143', '\x3', '\x2', '\x2', '\x2', '\x145', '\x146', '\x3', 
		'\x2', '\x2', '\x2', '\x146', '\x14E', '\x3', '\x2', '\x2', '\x2', '\x147', 
		'\x148', '\a', '\x1C', '\x2', '\x2', '\x148', '\x149', '\a', '\x32', '\x2', 
		'\x2', '\x149', '\x14A', '\a', '\x6', '\x2', '\x2', '\x14A', '\x14B', 
		'\x5', '\x14', '\v', '\x2', '\x14B', '\x14C', '\a', '\v', '\x2', '\x2', 
		'\x14C', '\x14D', '\x5', '\x1C', '\xF', '\x2', '\x14D', '\x14F', '\x3', 
		'\x2', '\x2', '\x2', '\x14E', '\x147', '\x3', '\x2', '\x2', '\x2', '\x14E', 
		'\x14F', '\x3', '\x2', '\x2', '\x2', '\x14F', '\x150', '\x3', '\x2', '\x2', 
		'\x2', '\x150', '\x151', '\a', '(', '\x2', '\x2', '\x151', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x152', '\x157', '\a', '\x32', '\x2', '\x2', '\x153', 
		'\x154', '\a', '\b', '\x2', '\x2', '\x154', '\x156', '\a', '\x32', '\x2', 
		'\x2', '\x155', '\x153', '\x3', '\x2', '\x2', '\x2', '\x156', '\x159', 
		'\x3', '\x2', '\x2', '\x2', '\x157', '\x155', '\x3', '\x2', '\x2', '\x2', 
		'\x157', '\x158', '\x3', '\x2', '\x2', '\x2', '\x158', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x159', '\x157', '\x3', '\x2', '\x2', '\x2', '\x15A', 
		'\x15B', '\a', '\x5', '\x2', '\x2', '\x15B', '\x15C', '\a', ')', '\x2', 
		'\x2', '\x15C', '\x45', '\x3', '\x2', '\x2', '\x2', '\x15D', '\x162', 
		'\x5', '\x1C', '\xF', '\x2', '\x15E', '\x15F', '\a', '\x1A', '\x2', '\x2', 
		'\x15F', '\x161', '\x5', '\x1C', '\xF', '\x2', '\x160', '\x15E', '\x3', 
		'\x2', '\x2', '\x2', '\x161', '\x164', '\x3', '\x2', '\x2', '\x2', '\x162', 
		'\x160', '\x3', '\x2', '\x2', '\x2', '\x162', '\x163', '\x3', '\x2', '\x2', 
		'\x2', '\x163', 'G', '\x3', '\x2', '\x2', '\x2', '\x164', '\x162', '\x3', 
		'\x2', '\x2', '\x2', '\x165', '\x166', '\t', '\x4', '\x2', '\x2', '\x166', 
		'I', '\x3', '\x2', '\x2', '\x2', '\x167', '\x168', '\t', '\x5', '\x2', 
		'\x2', '\x168', 'K', '\x3', '\x2', '\x2', '\x2', '\x169', '\x16A', '\t', 
		'\x6', '\x2', '\x2', '\x16A', 'M', '\x3', '\x2', '\x2', '\x2', '\x16B', 
		'\x16C', '\t', '\a', '\x2', '\x2', '\x16C', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x16D', '\x16E', '\t', '\b', '\x2', '\x2', '\x16E', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x16F', '\x170', '\t', '\t', '\x2', '\x2', '\x170', 
		'S', '\x3', '\x2', '\x2', '\x2', '&', '[', '\x62', 'j', 'p', 'u', '{', 
		'\x85', '\x92', '\x95', '\x99', '\xA3', '\xB2', '\xB6', '\xCA', '\xD1', 
		'\xD9', '\xE2', '\xE9', '\xF0', '\xFB', '\xFF', '\x102', '\x108', '\x111', 
		'\x11D', '\x120', '\x127', '\x12C', '\x12F', '\x132', '\x135', '\x140', 
		'\x145', '\x14E', '\x157', '\x162',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
