//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ocl.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="OclParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IOclVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.oclFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOclFile([NotNull] OclParser.OclFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.packageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageName([NotNull] OclParser.PackageNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.oclExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOclExpressions([NotNull] OclParser.OclExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] OclParser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.contextDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContextDeclaration([NotNull] OclParser.ContextDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.classifierContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassifierContext([NotNull] OclParser.ClassifierContextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.operationContext"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationContext([NotNull] OclParser.OperationContextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.operationName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationName([NotNull] OclParser.OperationNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList([NotNull] OclParser.FormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] OclParser.TypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.collectionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionType([NotNull] OclParser.CollectionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.oclExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOclExpression([NotNull] OclParser.OclExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] OclParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] OclParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.letExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetExpression([NotNull] OclParser.LetExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfExpression([NotNull] OclParser.IfExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.implExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplExpression([NotNull] OclParser.ImplExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.orExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpression([NotNull] OclParser.OrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] OclParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.eqExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqExpression([NotNull] OclParser.EqExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] OclParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] OclParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] OclParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] OclParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] OclParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] OclParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.propertyCallParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyCallParameters([NotNull] OclParser.PropertyCallParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] OclParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] OclParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiteral([NotNull] OclParser.EnumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeSpecifier([NotNull] OclParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.literalCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralCollection([NotNull] OclParser.LiteralCollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.collectionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionItem([NotNull] OclParser.CollectionItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.propertyCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyCall([NotNull] OclParser.PropertyCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.qualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiers([NotNull] OclParser.QualifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] OclParser.DeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.pathName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathName([NotNull] OclParser.PathNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.timeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeExpression([NotNull] OclParser.TimeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.actualParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualParameterList([NotNull] OclParser.ActualParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.orOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrOperator([NotNull] OclParser.OrOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.collectionKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectionKind([NotNull] OclParser.CollectionKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.eqOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqOperator([NotNull] OclParser.EqOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] OclParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOperator([NotNull] OclParser.AddOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.multiplyOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyOperator([NotNull] OclParser.MultiplyOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] OclParser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OclParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] OclParser.BooleanLiteralContext context);
}
