// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("WPF_Editor")]
[assembly: AssemblyProduct("REAL.NET")]
[assembly: AssemblyDescription("Domain-specific modeling toolkit")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]
[assembly: AssemblyConfiguration("Release")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string AssemblyTitle = "WPF_Editor";
        internal const string AssemblyProduct = "REAL.NET";
        internal const string AssemblyDescription = "Domain-specific modeling toolkit";
        internal const string AssemblyVersion = "0.1";
        internal const string AssemblyFileVersion = "0.1";
        internal const string AssemblyConfiguration = "Release";
    }
}