// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("WpfControlsLib")]
[assembly: AssemblyProduct("REAL.NET Repository Core")]
[assembly: AssemblyDescription("Domain-specific modeling repository")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]
[assembly: AssemblyConfiguration("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "WpfControlsLib";
        internal const System.String AssemblyProduct = "REAL.NET Repository Core";
        internal const System.String AssemblyDescription = "Domain-specific modeling repository";
        internal const System.String AssemblyVersion = "0.1";
        internal const System.String AssemblyFileVersion = "0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
