// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("EditorPrototype")]
[assembly: AssemblyProductAttribute("REAL.NET")]
[assembly: AssemblyDescriptionAttribute("Domain-specific modeling toolkit")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "EditorPrototype";
        internal const System.String AssemblyProduct = "REAL.NET";
        internal const System.String AssemblyDescription = "Domain-specific modeling toolkit";
        internal const System.String AssemblyVersion = "0.1";
        internal const System.String AssemblyFileVersion = "0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
